// Generated by scripts/build-content.mjs — do not edit by hand.
// Source: kohler.co.th collections index
// Harvested from /Collections and /browse/collections/ProductFamily/* in both languages by scripts/harvest-content.mjs.
//
// Every field carries th and en. Images are lifestyle ids, resolved against
// lib/lifestyle.generated.ts — never remote URLs, so nothing can hotlink or
// upscale. `status` says what the source page actually holds:
//   'ok'   — real content
//   'stub' — the page exists and is empty at source
//   'gone' — the URL 404s at source

// การ์ดบนหน้า /Collections มีจริงและมีเนื้อหา แต่ "หน้าตระกูลสินค้า" ที่มันลิงก์ไป
// ตอบ 404 ทุกหน้า — ยืนยันด้วยเบราว์เซอร์จริง ได้หน้า "Oops! We couldn't find"
// ทั้ง 14 ตระกูล × 2 ภาษา จึงบันทึกไว้เป็น gone ไม่ใช่แกล้งว่ามีข้อมูล
export type CollectionCard = {
  name: string
  blurb: { th: string; en: string }
  cta: { th: string; en: string }
  images: string[]
}

export type CollectionFamily = {
  slug: string
  path: string
  status: 'ok' | 'stub' | 'gone'
}

export const collectionCards: CollectionCard[] = [
  {
    name: 'Rêve™',
    blurb: { th: 'A bold, geometric style for a modern statement.', en: 'A bold, geometric style for a modern statement.' },
    cta: { th: 'Shop Rêve™ Collection', en: 'Shop Rêve™ Collection' },
    images: ['zaa19202-43', 'zaa19767-43', 'aab18535-43'],
  },
  {
    name: 'Escale™',
    blurb: { th: 'A timeless classic.', en: 'A timeless classic.' },
    cta: { th: 'Shop Escale™ Collection', en: 'Shop Escale™ Collection' },
    images: ['zac17365-rgb', 'zac17358-rgb'],
  },
  {
    name: 'Forefront ™',
    blurb: { th: 'Tranquility and natural beauty.', en: 'Tranquility and natural beauty.' },
    cta: { th: 'Shop Forefront™ Collection', en: 'Shop Forefront™ Collection' },
    images: ['forefront-02', 'forefront-01', 'forefront-03'],
  },
  {
    name: 'Bancroft ™',
    blurb: { th: 'A bold, geometric style for a modern statement.', en: 'A bold, geometric style for a modern statement.' },
    cta: { th: 'Shop Bancroft™ Collection', en: 'Shop Bancroft™ Collection' },
    images: ['bancroft-02', 'bancroft-03'],
  },
  {
    name: 'Portrait ®',
    blurb: { th: 'Sculpted lines and French Provincial charm.', en: 'Sculpted lines and French Provincial charm.' },
    cta: { th: 'Shop Portrait® Collection', en: 'Shop Portrait® Collection' },
    images: ['portrait-02', 'portrait-01', 'zab42431-rgb'],
  },
  {
    name: 'Tresham ™',
    blurb: { th: 'A fresh twist on a simple, Shaker-style furniture design.', en: 'A fresh twist on a simple, Shaker-style furniture design.' },
    cta: { th: 'Shop Tresham™ Collection', en: 'Shop Tresham™ Collection' },
    images: ['zab82176-rgb', 'zab82168-rgb'],
  },
  {
    name: 'Aleutian ™',
    blurb: { th: 'The Aleutian Suite is everyone\'s favorite.', en: 'The Aleutian Suite is everyone\'s favorite.' },
    cta: { th: 'Shop Aleutian™ Collection', en: 'Shop Aleutian™ Collection' },
    images: ['aleutian-02', 'aleutian-01', 'aleutian-02'],
  },
  {
    name: 'Maxispace ™',
    blurb: { th: 'Limited space; endless possibilities.', en: 'Limited space; endless possibilities.' },
    cta: { th: 'Shop Maxispace™ Collection', en: 'Shop Maxispace™ Collection' },
    images: ['maxispace-01', 'maxispace-03b'],
  },
  {
    name: 'Karess ™',
    blurb: { th: 'Curves and soft lines for a tranquil sanctuary.', en: 'Curves and soft lines for a tranquil sanctuary.' },
    cta: { th: 'Shop Karess™ Collection', en: 'Shop Karess™ Collection' },
    images: ['karess-02', 'karess-01', 'karess-03'],
  },
  {
    name: 'Ove ™',
    blurb: { th: 'A modern statement of refinement.', en: 'A modern statement of refinement.' },
    cta: { th: 'Shop Ove™ Collection', en: 'Shop Ove™ Collection' },
    images: ['ove-01', 'ove-02'],
  },
  {
    name: 'Archer ™',
    blurb: { th: 'An alluring blend of craftsman furniture and fine jewelry.', en: 'An alluring blend of craftsman furniture and fine jewelry.' },
    cta: { th: 'Shop Archer™ Collection', en: 'Shop Archer™ Collection' },
    images: ['aaa68056-rgb', 'aaa68094-rgb', 'aaa60312-rgb'],
  },
  {
    name: 'Kelston ™',
    blurb: { th: 'A unique blend of traditional and modern design.', en: 'A unique blend of traditional and modern design.' },
    cta: { th: 'Shop Kelston™ Collection', en: 'Shop Kelston™ Collection' },
    images: ['zaa90068-rgb', 'zaa88796-rgb'],
  },
  {
    name: 'Cimarron ™',
    blurb: { th: 'A versatile transitional style with universal appeal.', en: 'A versatile transitional style with universal appeal.' },
    cta: { th: 'Shop Cimarron™ Collection', en: 'Shop Cimarron™ Collection' },
    images: ['zab31995-rgb', 'zaa99845-rgb', 'zaa99845-rgb'],
  },
  {
    name: 'Flexispace ™',
    blurb: { th: 'Small space, big ideas.', en: 'Small space, big ideas.' },
    cta: { th: 'Shop Flexispace™ Collection', en: 'Shop Flexispace™ Collection' },
    images: ['zaa08191-rgb', 'aaa88333-rgb'],
  },
  {
    name: 'Serif ™',
    blurb: { th: 'Timeless contemporary elegance.', en: 'Timeless contemporary elegance.' },
    cta: { th: 'Shop Serif™ Collection', en: 'Shop Serif™ Collection' },
    images: ['ccc12361-43', 'bbb18895-43', 'zaa81538-rgb'],
  },
  {
    name: 'Patio ™',
    blurb: { th: 'Modern simplicity.', en: 'Modern simplicity.' },
    cta: { th: 'Shop Patio™ Collection', en: 'Shop Patio™ Collection' },
    images: ['aab14759', 'zab95711-rgb'],
  },
]

/** ทุกหน้าตระกูลสินค้าหายจากต้นทาง ณ วันที่เก็บข้อมูล */
export const collectionFamilies: CollectionFamily[] = [
  { slug: 'aleutian', path: '/browse/collections/ProductFamily/aleutian', status: 'gone' },
  { slug: 'archerr', path: '/browse/collections/ProductFamily/archerr', status: 'gone' },
  { slug: 'cimarron', path: '/browse/collections/ProductFamily/cimarron', status: 'gone' },
  { slug: 'escale', path: '/browse/collections/ProductFamily/escale', status: 'gone' },
  { slug: 'flexispace', path: '/browse/collections/ProductFamily/flexispace', status: 'gone' },
  { slug: 'forefront', path: '/browse/collections/ProductFamily/forefront', status: 'gone' },
  { slug: 'karess', path: '/browse/collections/ProductFamily/karess', status: 'gone' },
  { slug: 'kelston', path: '/browse/collections/ProductFamily/kelston', status: 'gone' },
  { slug: 'maxispace', path: '/browse/collections/ProductFamily/maxispace', status: 'gone' },
  { slug: 'ove', path: '/browse/collections/ProductFamily/ove', status: 'gone' },
  { slug: 'patio', path: '/browse/collections/ProductFamily/patio', status: 'gone' },
  { slug: 'portraitr', path: '/browse/collections/ProductFamily/portraitr', status: 'gone' },
  { slug: 'serifr', path: '/browse/collections/ProductFamily/serifr', status: 'gone' },
  { slug: 'treshamr', path: '/browse/collections/ProductFamily/treshamr', status: 'gone' },
]
