// Generated by scripts/build-content.mjs — do not edit by hand.
// Source: kohler.co.th shopping guides
// Harvested from /shoppingguide/* in both languages by scripts/harvest-content.mjs.
//
// Every field carries th and en. Images are lifestyle ids, resolved against
// lib/lifestyle.generated.ts — never remote URLs, so nothing can hotlink or
// upscale. `status` says what the source page actually holds:
//   'ok'   — real content
//   'stub' — the page exists and is empty at source
//   'gone' — the URL 404s at source

export type GuideOption = {
  label: { th: string; en: string }
  /** false = ต้นทางฉบับอังกฤษไม่มีตัวเลือกนี้ ค่า en จึงเป็นภาษาไทยที่ตกกลับมา */
  enAvailable: boolean
  /** ลิงก์กรองสินค้าของต้นทาง เก็บไว้เป็นข้อมูล ไม่ได้ชี้ไปที่เว็บนี้ */
  href: string
  image: string | null
}

export type GuideSection = {
  title: { th: string; en: string }
  /** false = บล็อกนี้ไม่มีในฉบับอังกฤษของหน้าเดียวกัน */
  enAvailable: boolean
  options: GuideOption[]
}

export type Guide = {
  slug: string
  path: string
  status: 'ok' | 'stub' | 'gone'
  sections: GuideSection[]
}

export const guides: Guide[] = [
  {
    slug: 'bathroom-accessories',
    path: '/shoppingguide/bathroom-accessories',
    status: 'ok',
    sections: [
      {
        title: { th: 'เลือกตามประเภท', en: 'Select by type' },
        enAvailable: true,
        options: [
          { label: { th: 'ราวแขวนผ้าและห่วงแขวนผ้า', en: 'Towel bar & ring' }, enAvailable: true, href: '', image: 'towel-bar-ring' },
          { label: { th: 'ที่ใส่กระดาษชำระ', en: 'Toilet paper holder' }, enAvailable: true, href: '/browse/bathroom/Categories/bathroom-accessories/ProductType/ที่ใส่กระดาษชำระ', image: '02-toilet-paper-holder' },
          { label: { th: 'ขอสำหรับแขวนผ้า', en: 'Robe hook' }, enAvailable: true, href: '/browse/bathroom/Categories/bathroom-accessories/ProductType/ขอแขวนผ้า', image: '03-robe-hook' },
          { label: { th: 'อื่นๆ', en: 'Others' }, enAvailable: true, href: '/browse/bathroom/Categories/bathroom-accessories/ProductType/อื่นๆ', image: '06-others' },
        ],
      },
      {
        title: { th: 'เลือกตามสี', en: 'Select by colour/finish' },
        enAvailable: true,
        options: [
          { label: { th: 'โครเมียม', en: 'Polished Chrome' }, enAvailable: true, href: '/browse/bathroom/Categories/bathroom-accessories/Color/swatch_CP', image: '01-cp' },
          { label: { th: 'บรอนซ์ปัดลาย', en: 'Brushed Bronze' }, enAvailable: true, href: '/browse/bathroom/Categories/bathroom-accessories/Color/swatch_BV', image: '05-bv' },
          { label: { th: 'สีนิกเกิ้ลปัดลาย', en: 'Vibrant Brushed Nickel' }, enAvailable: true, href: '/browse/bathroom/Categories/bathroom-accessories/Color/swatch_BN', image: '06-bn' },
          { label: { th: 'ทองแดงรมดำ', en: 'Oil-Rubbed Bronze' }, enAvailable: true, href: '/browse/bathroom/Categories/bathroom-accessories/Color/swatch_2BZ', image: '07-2bz' },
          { label: { th: 'อื่นๆ', en: 'Others' }, enAvailable: true, href: '/results/Categories/bathroom-accessories?search=Others&type=product', image: 'shopping-guide-bathroom-accessories-others' },
        ],
      },
      {
        title: { th: 'เลือกตามสินค้ายอดนิยม', en: 'select by most popular products' },
        enAvailable: true,
        options: [
          { label: { th: 'LOURE Double Hotelier', en: 'LOURE Double Hotelier' }, enAvailable: false, href: '/productDetails/11745T?skuid=11745T-CP', image: 'loure-double-hotelier-k-11745t-cp' },
        ],
      },
    ],
  },
  {
    slug: 'bathroom-faucets',
    path: '/shoppingguide/bathroom-faucets',
    status: 'ok',
    sections: [
      {
        title: { th: 'Select by type', en: 'Select by type' },
        enAvailable: false,
        options: [
          { label: { th: 'ก๊อกอ่างล้างหน้า', en: 'Lavatory Faucet' }, enAvailable: true, href: '/browse/bathroom/Categories/bathroom-faucets/ProductType/ก๊อกผสมอ่างล้างหน้า', image: 'lavatory-faucet' },
        ],
      },
      {
        title: { th: 'Select by bathroom style', en: 'Select by bathroom style' },
        enAvailable: false,
        options: [
          { label: { th: 'ร่วมสมัย', en: 'Contemporary' }, enAvailable: true, href: '/browse/bathroom/Categories/bathroom-faucets/Style/ร่วมสมัย', image: '36-comtemporary' },
          { label: { th: 'ยุคเปลี่ยนผ่านสู่ความร่วมสมัย', en: 'Transitional' }, enAvailable: true, href: '/browse/bathroom/Categories/bathroom-faucets/Style/ยุคเปลี่ยนผ่านสู่ความร่วมสมัย', image: '37-transitional' },
          { label: { th: 'คลาสสิก', en: 'Classic' }, enAvailable: true, href: '/browse/bathroom/Categories/bathroom-faucets/Style/คลาสสิก', image: '35-classic' },
        ],
      },
      {
        title: { th: 'Select by installation type (Lavatory Faucet)', en: 'Select by installation type (Lavatory Faucet)' },
        enAvailable: false,
        options: [
          { label: { th: 'รูเดี่ยว', en: 'One hole' }, enAvailable: true, href: '', image: 'one-hole' },
        ],
      },
      {
        title: { th: 'Select by installation type (Bathtub Faucet)', en: 'Select by installation type (Bathtub Faucet)' },
        enAvailable: false,
        options: [
          { label: { th: 'แบบติดตั้งบนอ่าง', en: 'แบบติดตั้งบนอ่าง' }, enAvailable: false, href: '/browse/bathroom/Categories/bathroom-faucets/InstallationType/ติดผนัง', image: '04-deck-mount' },
          { label: { th: 'แบบติดตั้งบนพื้น', en: 'แบบติดตั้งบนพื้น' }, enAvailable: false, href: '/browse/bathroom/Categories/bathroom-faucets/InstallationType/ติดผนัง', image: 'floor-mount' },
        ],
      },
      {
        title: { th: 'Select by most popular products', en: 'Select by most popular products' },
        enAvailable: false,
        options: [
          { label: { th: 'COMPONENTS', en: 'COMPONENTS' }, enAvailable: false, href: '/productDetails/77967T?skuid=77967T-CP', image: 'components-77967' },
          { label: { th: 'COMPOSED', en: 'COMPOSED' }, enAvailable: false, href: '/results/Categories/bathroom-faucets?search=Composed™&type=product', image: 'composed-73050' },
          { label: { th: 'AVID', en: 'AVID' }, enAvailable: false, href: '/productDetails/97345T-4?skuid=97345T-4-CP', image: 'avid-97345' },
          { label: { th: 'ALEO', en: 'ALEO' }, enAvailable: false, href: '/productDetails/72275T-4?skuid=72275T-4-CP', image: 'aleo-72275' },
          { label: { th: 'PURIST', en: 'PURIST' }, enAvailable: false, href: '/results?search=14406', image: 'purist-14406' },
          { label: { th: 'TAUT', en: 'TAUT' }, enAvailable: false, href: '/results?search=74013', image: 'taut-74013' },
        ],
      },
    ],
  },
  {
    slug: 'bathroom-furniture',
    path: '/shoppingguide/bathroom-furniture',
    status: 'ok',
    sections: [
      {
        title: { th: 'เลือกตามสี', en: 'เลือกตามสี' },
        enAvailable: false,
        options: [
          { label: { th: 'อื่นๆ', en: 'อื่นๆ' }, enAvailable: false, href: '/browse/bathroom/Categories/bathroom-furniture', image: 'others' },
        ],
      },
      {
        title: { th: 'เลือกตามสไตล์ห้องน้ำ', en: 'Select by bathroom style' },
        enAvailable: true,
        options: [
          { label: { th: 'ร่วมสมัย', en: 'Contemporary' }, enAvailable: true, href: '/browse/bathroom/Categories/bathroom-furniture/Style/ร่วมสมัย', image: '36-comtemporary' },
          { label: { th: 'ยุคเปลี่ยนผ่านสู่ความร่วมสมัย', en: 'Transitional' }, enAvailable: true, href: '/browse/bathroom/Categories/bathroom-furniture/Style/ยุคเปลี่ยนผ่านสู่ความร่วมสมัย', image: '37-transitional' },
          { label: { th: 'คลาสสิก', en: 'Classic' }, enAvailable: true, href: '/browse/bathroom/Categories/bathroom-furniture/Style/คลาสสิก', image: '35-classic' },
        ],
      },
      {
        title: { th: 'เลือกตามสินค้าที่ได้รับความนิยมสูงสุด', en: 'Select by most popular product' },
        enAvailable: true,
        options: [
          { label: { th: 'ตู้เฟอร์นิเจอร์สำหรับอ่างล้างหน้า รุ่นแฟมิลี่แคร์ 800', en: 'Family Care Bathroom Furniture 800mm' }, enAvailable: true, href: 'https://www.kohlerasiapacific.com/productDetails/31501T-L?skuid=31501T-L-PD1', image: '31501t-pd1' },
          { label: { th: 'ตู้เฟอร์นิเจอร์สำหรับอ่างล้างหน้า รุ่นแม็กซี่ สเปซ 900', en: 'Maxispace Bathroom Cabinet 35"' }, enAvailable: true, href: 'https://www.kohlerasiapacific.com/productDetails/20020T?skuid=20020T-H14', image: 'k-20020t-m-h14' },
          { label: { th: 'ตู้เฟอร์นิเจอร์รุ่นอลูเชียน', en: 'Aleutian Bathroom Cabinet 35"' }, enAvailable: true, href: 'https://www.kohlerasiapacific.com/productDetails/45764T?skuid=45764T-0', image: 'k-45764t-0' },
          { label: { th: 'ตู้เฟอร์นิเจอร์สำหรับอ่างล้างหน้า รุ่นโมเดิร์นไลฟ์ 900', en: 'ModernLife 35\'\' Bathroom Cabinet' }, enAvailable: true, href: '', image: 'k-77138t-s01' },
        ],
      },
    ],
  },
  {
    slug: 'bathtubs',
    path: '/shoppingguide/bathtubs',
    status: 'ok',
    sections: [
      {
        title: { th: 'เลือกตามสไตล์ห้องน้ำ', en: 'Select by bathroom style' },
        enAvailable: true,
        options: [
          { label: { th: 'ร่วมสมัย', en: 'Contemporary' }, enAvailable: true, href: '/browse/bathroom/Categories/bathing/Style/ร่วมสมัย', image: '36-comtemporary' },
          { label: { th: 'ยุคเปลี่ยนผ่านสู่ความร่วมสมัย', en: 'Transitional' }, enAvailable: true, href: '/browse/bathroom/Categories/bathing/Style/ยุคเปลี่ยนผ่านสู่ความร่วมสมัย', image: '37-transitional' },
          { label: { th: 'คลาสสิก', en: 'Classic' }, enAvailable: true, href: '/browse/bathroom/Categories/bathing/Style/คลาสสิก', image: '35-classic' },
        ],
      },
      {
        title: { th: 'เลือกตามวัสดุ', en: 'Select by material' },
        enAvailable: true,
        options: [
          { label: { th: 'ลิโธคาส', en: 'Lithocast' }, enAvailable: true, href: '/browse/bathroom/Categories/bathing/Material/ลิโธคาส', image: 'lithoscat' },
          { label: { th: 'อะครีลิค', en: 'Acrylic' }, enAvailable: true, href: '/browse/bathroom/Categories/bathing/Material/อะคริลิค', image: 'acrylic' },
        ],
      },
      {
        title: { th: 'สินค้าที่คุณอาจสนใจ', en: 'You may also be interested in' },
        enAvailable: true,
        options: [
          { label: { th: 'ก๊อกอ่างอาบน้ำ', en: 'Bathtub faucet' }, enAvailable: true, href: '', image: 'bathtub-faucet' },
          { label: { th: 'อุปกรณ์อ่างอาบน้ำ', en: 'Bathtub accessories' }, enAvailable: true, href: '', image: 'bathtub-accessories' },
        ],
      },
    ],
  },
  {
    slug: 'bidet-seat',
    path: '/shoppingguide/bidet-seat',
    status: 'ok',
    sections: [
      {
        title: { th: 'เลือกตามสินค้ายอดนิยม', en: 'Select by most popular products' },
        enAvailable: true,
        options: [
          { label: { th: 'C3-050', en: 'C3-050' }, enAvailable: false, href: '', image: 'c3-050-18751' },
          { label: { th: 'C3-150', en: 'C3-150' }, enAvailable: false, href: '', image: 'c3-150-8297' },
        ],
      },
    ],
  },
  {
    slug: 'commercial',
    path: '/shoppingguide/commercial',
    status: 'ok',
    sections: [
      {
        title: { th: 'เลือกตามประเภท', en: 'Select by type' },
        enAvailable: true,
        options: [
          { label: { th: 'แป้นเซ็นเซอร์', en: 'Sensor' }, enAvailable: true, href: '', image: '03-sensors' },
          { label: { th: 'โถปัสสาวะชาย', en: 'Urinal' }, enAvailable: true, href: '/browse/bathroom/Categories/commercial-bathroom/ProductType/โถปัสสาวะชาย', image: '01-urinals' },
        ],
      },
      {
        title: { th: 'เลือกตามสินค้ายอดนิยม', en: 'Select by most popular products' },
        enAvailable: true,
        options: [
          { label: { th: 'โถปัสสาวะชาย รุ่น บาดั้น ทัชเลส', en: 'MODERNLIFE Urinal' }, enAvailable: true, href: '/productDetails/4915T?skuid=4915T-0', image: 'k-4915t-y-0-01' },
          { label: { th: 'โถปัสสาวะชาย รุ่นสตรัคทูร่า', en: 'STRUKTURA Urinal' }, enAvailable: true, href: '/productDetails/4986T-ER?skuid=4986T-ER-0', image: 'k-4986t-er-0-01' },
          { label: { th: 'ก๊อกเดี่ยวระบบเซ็นเซอร์รุ่นคูมิน', en: 'KUMIN SENSOR FAUCET' }, enAvailable: true, href: '/productDetails/18655X-E2?skuid=18655X-E2-CP', image: '18655t' },
          { label: { th: 'ก๊อกเดี่ยวระบบเซ็นเซอร์รุ่นสเตย์ท', en: 'STRAYT SENSOR FAUCET' }, enAvailable: true, href: '/productDetails/72866X-E2?skuid=72866X-E2-CP', image: '72866t' },
        ],
      },
    ],
  },
  {
    slug: 'kitchen-faucets',
    path: '/shoppingguide/kitchen-faucets',
    status: 'ok',
    sections: [
      {
        title: { th: 'เลือกตามสไตล์ห้องครัว', en: 'Select by kitchen style' },
        enAvailable: true,
        options: [
          { label: { th: 'ยุคเปลี่ยนผ่านสู่ความร่วมสมัย', en: 'Transitional' }, enAvailable: true, href: '/browse/kitchen/Categories/kitchen-faucets/Style/ยุคเปลี่ยนผ่านสู่ความร่วมสมัย', image: 'transitional-kitchen-style' },
          { label: { th: 'คลาสสิก', en: 'Classic' }, enAvailable: true, href: '/browse/kitchen/Categories/kitchen-faucets/Style/คลาสสิก', image: 'classical' },
        ],
      },
      {
        title: { th: 'เลือกตามสินค้ายอดนิยม', en: 'Select by most popular products' },
        enAvailable: true,
        options: [
          { label: { th: 'TAUT', en: 'TAUT' }, enAvailable: false, href: '/productDetails/74053T-4CD?skuid=74053T-4CD-CP', image: 'taut-kitchen-faucet' },
        ],
      },
    ],
  },
  {
    slug: 'kitchen-sinks',
    path: '/shoppingguide/kitchen-sinks',
    status: 'ok',
    sections: [
      {
        title: { th: 'เลือกตามการติดตั้ง', en: 'Select by installation' },
        enAvailable: true,
        options: [
          { label: { th: 'แบบฝังใต้เคาน์เตอร์', en: 'Under-mount' }, enAvailable: true, href: '/browse/kitchen/Categories/kitchen-sinks/InstallationType/แบบฝังใต้เคาน์เตอร์', image: '03-under-mount' },
        ],
      },
      {
        title: { th: 'เลือกตามรูปแบบหลุมอ่างล้างจาน', en: 'Select by bowl configuration' },
        enAvailable: true,
        options: [
          { label: { th: '1 หลุม', en: 'Single bowl' }, enAvailable: true, href: '/browse/kitchen/Categories/kitchen-sinks/BowlStyle/1+หลุม', image: '01-single-bowl' },
          { label: { th: '2 หลุม', en: 'Double-equal bowls' }, enAvailable: true, href: '/browse/kitchen/Categories/kitchen-sinks/BowlStyle/2+หลุม', image: '02-double-equal-bowls' },
          { label: { th: '1.5 หลุม', en: 'large/medium bowls' }, enAvailable: true, href: '/browse/kitchen/Categories/kitchen-sinks/BowlStyle/1+หลุมครึ่ง', image: '03-off-set-bowls' },
        ],
      },
      {
        title: { th: 'เลือกตามสไตล์ห้องครัว', en: 'Select by kitchen style' },
        enAvailable: true,
        options: [
          { label: { th: 'ร่วมสมัย', en: 'Contemporary' }, enAvailable: true, href: '/browse/kitchen/Categories/kitchen-sinks/Style/ร่วมสมัย', image: 'contemporary-kitchen-style' },
          { label: { th: 'ยุคเปลี่ยนผ่านสู่ความร่วมสมัย', en: 'Transitional' }, enAvailable: true, href: '/browse/kitchen/Categories/kitchen-sinks/Style/ยุคเปลี่ยนผ่านสู่ความร่วมสมัย', image: 'transitional-kitchen-style' },
          { label: { th: 'คลาสสิก', en: 'Classic' }, enAvailable: true, href: '/browse/kitchen/Categories/kitchen-sinks/Style/คลาสสิก', image: 'classical' },
        ],
      },
      {
        title: { th: 'เลือกตามความยาวของอ่างล้างจาน', en: 'เลือกตามความยาวของอ่างล้างจาน' },
        enAvailable: false,
        options: [
          { label: { th: '', en: '' }, enAvailable: false, href: '/browse/kitchen/Categories/kitchen-sinks?OverallLengthmmMax=600', image: '01-below-600-updated' },
          { label: { th: '', en: '' }, enAvailable: false, href: '/browse/kitchen/Categories/kitchen-sinks?OverallLengthmmMax=750', image: '02-750mm-updated' },
          { label: { th: '', en: '' }, enAvailable: false, href: '/browse/kitchen/Categories/kitchen-sinks?OverallLengthmmMax=900', image: '03-900mm-updated' },
          { label: { th: '', en: '' }, enAvailable: false, href: '/browse/kitchen/Categories/kitchen-sinks?OverallLengthmmMin=1050', image: '04-above-1050-updated' },
        ],
      },
      {
        title: { th: 'เลือกตามวัสดุ', en: 'เลือกตามวัสดุ' },
        enAvailable: false,
        options: [
          { label: { th: 'สแตนเลส สตีล', en: 'สแตนเลส สตีล' }, enAvailable: false, href: '/browse/kitchen/Categories/kitchen-sinks/Material/สแตนเลส+สตีล', image: '02-stainless-steel' },
        ],
      },
      {
        title: { th: 'เลือกตามสินค้ายอดนิยม', en: 'Select by most popular products' },
        enAvailable: true,
        options: [
          { label: { th: 'POISE', en: 'POISE' }, enAvailable: false, href: '/productDetails/3883X-F?skuid=3883X-F-NA', image: '01-poise-3880' },
          { label: { th: 'Prologue', en: 'Prologue' }, enAvailable: false, href: '/results/Categories/kitchen-sinks?search=Prologue&type=product', image: 'prologue' },
        ],
      },
    ],
  },
  {
    slug: 'lavatories',
    path: '/shoppingguide/lavatories',
    status: 'ok',
    sections: [
      {
        title: { th: 'เลือกตามการติดตั้ง', en: 'Select by installation' },
        enAvailable: true,
        options: [
          { label: { th: 'อ่างล้างหน้าแบบฝังบนเคาน์เตอร์', en: 'Self-rimming' }, enAvailable: true, href: '/browse/bathroom/Categories/lavatories/InstallationType/แบบฝังบนเคาน์เตอร์', image: 'self-rimming' },
          { label: { th: 'อ่างล้างหน้าวางบนตู้เฟอร์นิเจอร์', en: 'Vanity' }, enAvailable: true, href: '', image: 'vanity' },
          { label: { th: 'อ่างล้างหน้าแบบแขวนพร้อมขารองอ่าง', en: 'Pedestal' }, enAvailable: true, href: '', image: 'pedestal-2' },
        ],
      },
      {
        title: { th: 'เลือกตามรูปทรง', en: 'Select by shape' },
        enAvailable: true,
        options: [
          { label: { th: 'รูปทรงรี/ทรงกลม', en: 'Oval/ROUND' }, enAvailable: true, href: '/browse/bathroom/Categories/lavatories/Shape/Oval', image: 'oval-round' },
          { label: { th: 'รูปทรงเหลี่ยม', en: 'Rectangle/Square' }, enAvailable: true, href: '/browse/bathroom/Categories/lavatories/Shape/สี่เหลี่ยมจัตุรัส_x002f_สี่เหลี่ยม', image: 'rectangle-square' },
          { label: { th: 'รูปทรงพิเศษ', en: 'Unique' }, enAvailable: true, href: '/browse/bathroom/Categories/lavatories/Shape/อื่นๆ', image: 'unique' },
        ],
      },
      {
        title: { th: 'เลือกตามสไตล์ห้องน้ำ', en: 'Select by bathroom style' },
        enAvailable: true,
        options: [
          { label: { th: 'ร่วมสมัย', en: 'Contemporary' }, enAvailable: true, href: '/browse/bathroom/Categories/lavatories/Style/ร่วมสมัย', image: '36-comtemporary' },
          { label: { th: 'คลาสสิก', en: 'Classic' }, enAvailable: true, href: '/browse/bathroom/Categories/lavatories/Style/คลาสสิก', image: '35-classic' },
        ],
      },
      {
        title: { th: 'เลือกตามขนาด (วัดจากขอบอ่างถึงขอบอ่าง)', en: 'Select by length (from edge to edge)' },
        enAvailable: true,
        options: [
          { label: { th: '', en: '' }, enAvailable: false, href: '/browse/bathroom/Categories/lavatories/LengthRange/Below+450+mm', image: 'length-1' },
          { label: { th: '', en: '' }, enAvailable: false, href: '/browse/bathroom/Categories/lavatories/LengthRange/450-599+mm', image: 'length-2' },
          { label: { th: '', en: '' }, enAvailable: false, href: '/browse/bathroom/Categories/lavatories/LengthRange/600-799+mm', image: 'length-3' },
        ],
      },
      {
        title: { th: 'เลือกตามวัสดุ', en: 'Select by material' },
        enAvailable: true,
        options: [
          { label: { th: 'เซรามิกประเภทวิเทรียสไชน่า', en: 'Vitreous China' }, enAvailable: true, href: '/browse/bathroom/Categories/lavatories/Material/เซรามิกประเภทวิเทรียสไชน่า', image: 'vitreous-china' },
        ],
      },
      {
        title: { th: 'เลือกตามสินค้าที่ได้รับความนิยมสูงสุด', en: 'เลือกตามสินค้าที่ได้รับความนิยมสูงสุด' },
        enAvailable: false,
        options: [
          { label: { th: 'อ่างล้างหน้าแบบติดตั้งบนเคาน์เตอร์ รุ่น ชาลีซ', en: 'อ่างล้างหน้าแบบติดตั้งบนเคาน์เตอร์ รุ่น ชาลีซ' }, enAvailable: false, href: '/productDetails/14800X?skuid=14800X-0', image: 'chalice-vessel-lavatory' },
          { label: { th: 'อ่างล้างหน้าแบบฝังใต้เคาน์เตอร์ รุ่น เวอร์ติเคิล', en: 'อ่างล้างหน้าแบบฝังใต้เคาน์เตอร์ รุ่น เวอร์ติเคิล' }, enAvailable: false, href: '/productDetails/2889X?skuid=2889X-0', image: 'verticyl-under-counter-lavatory' },
        ],
      },
    ],
  },
  {
    slug: 'mirrored-cabinets',
    path: '/shoppingguide/mirrored-cabinets',
    status: 'ok',
    sections: [
      {
        title: { th: 'เลือกตามสไตล์ห้องน้ำ', en: 'Select by bathroom style' },
        enAvailable: true,
        options: [
          { label: { th: 'ร่วมสมัย', en: 'Contemporary' }, enAvailable: true, href: '/browse/bathroom/Categories/mirrored-cabinet/Style/ร่วมสมัย', image: '36-comtemporary' },
        ],
      },
      {
        title: { th: 'เลือกตามสินค้าที่ได้รับความนิยมสูงสุด', en: 'Select by most popular products' },
        enAvailable: true,
        options: [
          { label: { th: 'ตู้กระจกพร้อมไฟ รุ่นแฟมิลี่แคร์ 1000 มม.', en: 'FamilyCare Mirrored Cabinet 31\'\'' }, enAvailable: true, href: 'https://www.kohlerasiapacific.com/productDetails/25238T?skuid=25238T-NA', image: 'k-25238t-na' },
          { label: { th: 'ตู้กระจกพร้อมไฟ รุ่นนิว เวอเดรา 866มม.', en: 'New Verdera Mirrored Cabinet 34"' }, enAvailable: true, href: 'https://www.kohlerasiapacific.com/productDetails/78282T?skuid=78282T-NA', image: 'k-78282t-na1' },
          { label: { th: 'ตู้กระจกพร้อมไฟ รุ่นแม็กซี่ สเปซ 900มม.', en: 'MaxiSpace Mirror Cabinet 35\'\'' }, enAvailable: true, href: 'https://www.kohlerasiapacific.com/productDetails/96107T?skuid=96107T-NA', image: 'k-96107t-na1' },
          { label: { th: 'ตู้กระจกพร้อมไฟ รุ่นกรูมมิ่ง', en: 'Grooming Mirror Cabinet' }, enAvailable: true, href: '', image: 'k-24659t-l-na' },
        ],
      },
    ],
  },
  {
    slug: 'mirrors',
    path: '/shoppingguide/mirrors',
    status: 'ok',
    sections: [
      {
        title: { th: 'เลือกตามคุณสมบัติ', en: 'Select by lighting' },
        enAvailable: true,
        options: [
          { label: { th: 'กระจก/ตู้กระจก ไม่มีไฟ', en: 'Without lighting' }, enAvailable: true, href: '/browse/bathroom/Categories/mirror/LightingType/Without+lighting', image: 'without-lighting' },
          { label: { th: 'ตู้กระจกพร้อมไฟ', en: 'With lighting' }, enAvailable: true, href: '/browse/bathroom/Categories/mirror/LightingType/With+lighting', image: 'with-lighting' },
        ],
      },
      {
        title: { th: 'เลือกตามสไตล์ห้องน้ำ', en: 'Select by bathroom style' },
        enAvailable: true,
        options: [
          { label: { th: 'ร่วมสมัย', en: 'Contemporary' }, enAvailable: true, href: '/browse/bathroom/Categories/mirror/Style/ร่วมสมัย', image: '36-comtemporary' },
        ],
      },
      {
        title: { th: 'เลือกตามสินค้ายอดนิยม', en: 'Select by most popular products' },
        enAvailable: true,
        options: [
          { label: { th: 'POPLIN', en: 'POPLIN' }, enAvailable: false, href: '/results/Categories/mirror?search=99666&type=product', image: 'poplin-99666' },
        ],
      },
    ],
  },
  {
    slug: 'showering',
    path: '/shoppingguide/showering',
    status: 'ok',
    sections: [
      {
        title: { th: 'เลือกตามประเภท', en: 'Select by type' },
        enAvailable: true,
        options: [
          { label: { th: 'ก๊อกผสมยืนอาบ พร้อมชุดฝักบัวสายอ่อนและชุดฝักบัวก้านแข็ง รุ่นเออร', en: 'shower columns' }, enAvailable: true, href: '', image: 'urbanity-shower-column-23861' },
          { label: { th: 'โมดูโล', en: 'Valves and trims' }, enAvailable: true, href: '/browse/bathroom/Categories/bathroom-showering/ProductType/วาล์วและฝาครอบวาล์ว', image: 'modulo-bath-and-shower-trim-78024' },
          { label: { th: 'หัวฝักบัว', en: 'Handshowers' }, enAvailable: true, href: '/browse/bathroom/Categories/bathroom-showering/ProductType/ฝักบัวสายอ่อน', image: '02-handshower' },
          { label: { th: 'ตู้/ฉากกั้นอาบน้ำ', en: 'Shower doors' }, enAvailable: true, href: '/browse/bathroom/Categories/shower-doors', image: '05-shower-doors' },
          { label: { th: 'อุปกรณ์ฝักบัว', en: 'Shower fittings' }, enAvailable: true, href: '', image: '07-shower-fittings' },
        ],
      },
      {
        title: { th: 'เลือกตามสไตล์ห้องน้ำ', en: 'Select by bathroom style' },
        enAvailable: true,
        options: [
          { label: { th: 'ร่วมสมัย', en: 'Contemporary' }, enAvailable: true, href: '/browse/bathroom/Categories/bathroom-showering/Style/ร่วมสมัย', image: '36-comtemporary' },
          { label: { th: 'ยุคเปลี่ยนผ่านสู่ความร่วมสมัย', en: 'Transitional' }, enAvailable: true, href: '/browse/bathroom/Categories/bathroom-showering/Style/ยุคเปลี่ยนผ่านสู่ความร่วมสมัย', image: '37-transitional' },
          { label: { th: 'คลาสสิก', en: 'Classic' }, enAvailable: true, href: '/browse/bathroom/Categories/bathroom-showering/Style/คลาสสิก', image: '35-classic' },
        ],
      },
      {
        title: { th: 'เลือกตามสินค้ายอดนิยม', en: 'Select by most popular products' },
        enAvailable: true,
        options: [
          { label: { th: 'Aleo Shower Column', en: 'Aleo Shower Column' }, enAvailable: false, href: '', image: 'aleo-shower-column-97821' },
          { label: { th: 'Modulo Bath and Shower Trim', en: 'Modulo Bath and Shower Trim' }, enAvailable: false, href: '/productDetails/73108X-4?skuid=73108X-4-CP', image: 'modulo-bath-and-shower-trim-78024' },
          { label: { th: 'Urbanity+ Shower Column', en: 'Urbanity+ Shower Column' }, enAvailable: false, href: '', image: 'urbanity-shower-column-23861' },
          { label: { th: 'Exhale', en: 'Exhale' }, enAvailable: false, href: '/productDetails/33001X?skuid=33001X-CP', image: 'exhale' },
        ],
      },
    ],
  },
  {
    slug: 'toilets',
    path: '/shoppingguide/toilets',
    status: 'ok',
    sections: [
      {
        title: { th: 'เลือกตามประเภท', en: 'Select by type' },
        enAvailable: true,
        options: [
          { label: { th: 'สุขภัณฑ์แบบชิ้นเดียว พร้อมระบบชำระล้างแบบอัตโนมัติ', en: 'Intelligent toilet' }, enAvailable: true, href: '/results?search=Intelligent+toilet', image: 'intelligenttoilet3' },
          { label: { th: 'สุขภัณฑ์แบบชิ้นเดียว', en: 'One-piece' }, enAvailable: true, href: '/browse/bathroom/Categories/toilets/ToiletType/สุขภัณฑ์แบบชิ้นเดียว', image: 'onepiecetoilet2' },
          { label: { th: 'สุขภัณฑ์แบบสองชิ้น', en: 'สุขภัณฑ์แบบสองชิ้น' }, enAvailable: false, href: '/browse/bathroom/Categories/toilets/ToiletType/สุขภัณฑ์แบบสองชิ้น', image: 'twopiecetoilet5' },
          { label: { th: 'ประเภทสินค้าทั้งหมด', en: 'ALL TYPES' }, enAvailable: true, href: '/browse/bathroom/Categories/toilets', image: '460x353' },
        ],
      },
      {
        title: { th: 'เลือกตามสไตล์ห้องน้ำ', en: 'Select by bathroom style' },
        enAvailable: true,
        options: [
          { label: { th: 'ยุคเปลี่ยนผ่านสู่ความร่วมสมัย', en: 'Transitional' }, enAvailable: true, href: '/browse/bathroom/Categories/toilets/Style/ยุคเปลี่ยนผ่านสู่ความร่วมสมัย', image: '37-transitional' },
          { label: { th: 'ร่วมสมัย', en: 'contemporary' }, enAvailable: true, href: '/browse/bathroom/Categories/toilets/Style/ร่วมสมัย', image: '36-comtemporary' },
        ],
      },
      {
        title: { th: 'เลือกตามขนาดของโถสุขภัณฑ์', en: 'Select by bowl shape' },
        enAvailable: true,
        options: [
          { label: { th: 'หน้ายาว', en: 'Elongated' }, enAvailable: true, href: '', image: 'elongated-bowl' },
          { label: { th: 'หน้าสั้น', en: 'Rounded' }, enAvailable: true, href: '/browse/bathroom/Categories/toilets/BowlShape/กลม', image: 'rounded-bowl' },
        ],
      },
      {
        title: { th: 'เลือกตามสินค้าที่ได้รับความนิยมสูงสุด', en: 'Select by most popular products' },
        enAvailable: true,
        options: [
          { label: { th: 'อะแดร์', en: 'Adair' }, enAvailable: true, href: '', image: 'adair0' },
          { label: { th: 'โมเดิร์นไลฟ์', en: 'ModernLife' }, enAvailable: true, href: '', image: 'modernlife0' },
          { label: { th: 'สุขภัณฑ์แบบชิ้นเดียว พร้อมระบบชำระล้างแบบอัตโนมัติ รุ่น เวล', en: 'Veil intelligent toilet' }, enAvailable: true, href: '', image: 'veil-intelligent-toilet0' },
          { label: { th: 'ซาน ราเฟล', en: 'San Raphael' }, enAvailable: true, href: '/results?search=San+Raphael', image: 'san-raphael0' },
        ],
      },
    ],
  },
]

export const getGuide = (slug: string): Guide | undefined => guides.find((g) => g.slug === slug)
