// Generated by scripts/build-content.mjs — do not edit by hand.
// Source: kohler.co.th idea hubs
// Harvested from /ideas/bathroomIdeas and /ideas/kitchenIdeas in both languages by scripts/harvest-content.mjs.
//
// Every field carries th and en. Images are lifestyle ids, resolved against
// lib/lifestyle.generated.ts — never remote URLs, so nothing can hotlink or
// upscale. `status` says what the source page actually holds:
//   'ok'   — real content
//   'stub' — the page exists and is empty at source
//   'gone' — the URL 404s at source

export type IdeaItem = {
  /** ลิงก์บทความบนต้นทาง — บทความเองอยู่ใน lib/posts.ts แล้ว */
  href: string
  heading: { th: string; en: string }
  blurb: { th: string; en: string }
  image: string | null
}

export type IdeaHub = {
  slug: string
  path: string
  status: 'ok' | 'stub' | 'gone'
  title: { th: string; en: string }
  items: IdeaItem[]
}

export const ideaHubs: IdeaHub[] = [
  {
    slug: 'bathroom',
    path: '/ideas/bathroomIdeas',
    status: 'ok',
    title: { th: 'Bathroom Ideas', en: 'BATHROOM IDEAS' },
    items: [
      { href: '/articles/innovative-bathroom-products-for-2022.html', heading: { th: 'สินค้านวัตกรรมในปี 2022', en: 'Innovative Bathroom Products for 2022' }, blurb: { th: 'เปลี่ยนห้องน้ำธรรมดาให้กลายเป็นสปาด้วยสินค้าที่ล้ำสมัย', en: 'Turn your bathroom into a home spa with cutting-edge products.' }, image: '2022-most-innovative-bathroom-products-moxie-numi-gcs-secondary-banner-290-x-232' },
      { href: '/articles/small-bathroom-space.html', heading: { th: 'ห้องน้ำขนาดเล็ก', en: 'Small Bathrooms' }, blurb: { th: 'วิธีจัดการห้องน้ำขนาดเล็ก ให้มีพื้นที่ใช้สอยเพิ่มขึ้น', en: 'Maximize your space with design and functionality' }, image: 'maxispace-secondary-banner-290x232' },
      { href: '/articles/cleaner-toilets-revolution-360.html', heading: { th: 'Bathroom Cleanliness Improves Health', en: 'Level up With Bidet Seats' }, blurb: { th: 'วิธีที่สุขภัณฑ์จะช่วยเสริมสร้างสุขอนามัยให้ห้องน้ำของคุณได้', en: 'All you need to know about bidet seats' }, image: 'secandary-banner-rev360' },
      { href: '/articles/9-tips-for-small-bathrooms.html', heading: { th: 'เคล็ดลับ 9 ข้อ สำหรับการตกแต่งห้องน้ำขนาดเล็ก', en: 'Bathroom Cleanliness Improves Health' }, blurb: { th: 'เรียนรู้วิธีการทำให้ห้องน้ำมีพื้นที่ขนาดเล็กเกิดประโยชน์สูงสุด โดยไม่จำเป็นต้องดัดแปลงห้องใหม่', en: 'Learn how a toilet can keep your bathroom cleaner' }, image: 'zab21360-rgb' },
      { href: '/articles/bath-design-aging-gracefully-article.html', heading: { th: 'การออกแบบห้องน้ำ: งามสง่าตามกาลเวลา', en: '9 Tips for Small Bathrooms' }, blurb: { th: 'ด้วยคุณสมบัติพิเศษที่ทำให้คุณรู้สึกสะดวกสบาย และยังเพิ่มความสวยงามโออ่าให้กับห้องน้ำของคุณ', en: 'Learn how to make the most of a petite space — without remodeling.' }, image: 'aab15367-rgb' },
      { href: '/articles/bathroom-design-tips-article.html', heading: { th: 'เคล็ดลับการออกแบบ ห้องน้ำ', en: 'Bath Design: Aging Gracefully' }, blurb: { th: 'สถานที่เริ่มต้นวันใหม่และส่งท้ายของคุณ ควรเป็นสถานที่เงียบสงบและเปี่ยมพลังตามที่คุณปรารถนา', en: 'There are features that can help you stay comfortable while enhancing your bathroom\'s beauty and elegance.' }, image: 'zab60076-rgb' },
      { href: '/articles/designing-the-perfect-powder-room-article.html', heading: { th: 'การออกแบบห้องแต่งตัวของคุณให้สมบูรณ์แบบ', en: 'Bathroom Design Tips' }, blurb: { th: 'ดูวิธีการสร้างพื้นที่ขนาดเล็กเพื่อแสดงให้เห็นถึงสไตล์ที่แท้จริงของคุณ', en: 'The place you begin and end each day can be as calming or energizing as you desire.' }, image: 'zac11288-rgb' },
      { href: '/articles/easy-affordable-bath-upgrades.html', heading: { th: 'ปรับปรุงห้องน้ำของคุณอย่างง่ายดาย', en: 'Designing the Perfect Powder Room' }, blurb: { th: 'วิธีการสร้างพื้นที่ขนาดเล็กเพื่อแสดงให้เห็นถึงสไตล์ที่แท้จริงของคุณ', en: 'See how to create a small space that really shows off your style.' }, image: 'zab65968-rgb' },
      { href: '/articles/pure-joy-designing-an-all-white-bath-article.html', heading: { th: 'การออกแบบห้องน้ำ ด้วยโทนสีขาวทั้งหมด', en: 'Easy, Affordable Bath Upgrades' }, blurb: { th: 'ดูวิธีการสร้างพื้นที่ขนาดเล็กเพื่อแสดงให้เห็นถึงสไตล์ที่แท้จริงของคุณ', en: 'See how to create a small space that really shows off your style.' }, image: 'aaa80571-1800x800' },
      { href: '/articles/spa-style-bathrooms-luxury-that-lasts-article.html', heading: { th: 'ห้องอาบน้ำสไตล์สปา ความหรูหรานิรันดร์กาล', en: 'Pure Joy: Designing an All-White Bath' }, blurb: { th: 'ความหรูหราเป็นมากกว่าแค่สไตล์ และยังทรงคุณค่าอีกด้วย', en: 'See how to create a small space that really shows off your style.' }, image: 'zac16296-rgb' },
    ],
  },
  {
    slug: 'kitchen',
    path: '/ideas/kitchenIdeas',
    status: 'ok',
    title: { th: 'Kitchen Ideas', en: 'KITCHEN IDEAS' },
    items: [
      { href: '/articles/choosing-the-perfect-kitchen-faucets.html', heading: { th: 'ออกแบบห้องครัวในฝันของคุณ', en: 'Kitchen Space Reimagined' }, blurb: { th: 'ห้องครัวคือหัวใจสำคัญของบ้าน', en: 'Clever home chefs design the heart of the home.' }, image: 'malleco-article-image-460x353-01' },
      { href: '/articles/6-ideas-for-a-colorful-kitchen.html', heading: { th: '6 ไอเดียสำหรับห้องครัวหลากสีสัน', en: '6 Ideas for a Colorful Kitchen' }, blurb: { th: 'เรียนรู้วิธีการทำให้พื้นที่ขนาดเล็กเกิดประโยชน์สูงสุด โดยไม่จำเป็นต้องดัดแปลงห้องใหม่', en: 'Learn how to make the most of a petite space — without remodeling.' }, image: 'zab86829-1800x800' },
      { href: '/articles/cooking-like-a-pro.html', heading: { th: 'ปรุงอาหารอย่างมืออาชีพ', en: 'Cooking Like a Pro' }, blurb: { th: 'ขอคำแนะนำเพื่อเนรมิตห้องครัวที่คู่ควรพร้อมมอบความเพลิดเพลินในการใช้งานให้คุณ', en: 'Get advice for creating a chef-worthy kitchen that\'s a joy to use.' }, image: 'zab57943-rgb' },
      { href: '/articles/functional-beauty-reconsidering-the-kitchen-sink-artilcle.html', heading: { th: 'ความงามที่มาพร้อม ฟังก์ชั่นการใช้งานกับ อ่างล้างจานในมุมมองใหม่', en: 'Functional Beauty: Reconsidering the Kitchen Sink' }, blurb: { th: 'มาค้นหาดูว่าก๊อกน้ำที่จะสร้างความงามให้กับห้องครัวของคุณและช่วยให้การเตรียมมื้ออาหารและการเก็บล้างทำได้ง่ายขึ้นได้อย่างไร', en: 'Discover how to find a faucet that will beautify your kitchen and make your prep and cleanup tasks easier.' }, image: 'zab64028-1800x800' },
      { href: '/articles/reconsidering-the-kitchen-faucet-article.html', heading: { th: 'ลองนึกถึงก๊อกน้ำห้องครัว', en: 'Reconsidering the Kitchen Faucet' }, blurb: { th: 'มาค้นหากันว่าก๊อกน้ำที่จะสร้างความงามให้กับห้องครัวของคุณและช่วยให้การเตรียมมื้ออาหารและการเก็บล้างทำได้ง่ายขึ้นได้อย่างไร', en: 'Discover how to find a faucet that will beautify your kitchen and make your prep and cleanup tasks easier.' }, image: 'zab85993-rgb' },
      { href: '/articles/the-pale-neutral-kitchen-trend-2-ways-to-get-inspired-article.html', heading: { th: 'เทรนด์ห้องครัวโทนสีกลางสีขาว', en: 'The Pale Neutral Kitchen Trend' }, blurb: { th: 'มาค้นหาดูว่าก๊อกน้ำที่จะสร้างความงามให้กับห้องครัวของคุณและช่วยให้การเตรียมมื้ออาหารและการเก็บล้างทำได้ง่ายขึ้นได้อย่างไร', en: 'Discover how to find a faucet that will beautify your kitchen and make your prep and cleanup tasks easier.' }, image: 'zab59998-1800x800-hollywoodhills' },
      { href: '/articles/why-kohler-stainless-steel-sinks-article.html', heading: { th: 'ทำไมจึงเลือกอ่างล้างจานสแตนเลสของโคห์เลอร์', en: 'Why Kohler Stainless Steel Sinks' }, blurb: { th: 'วัสดุคลาสสิกชิ้นนี้ไม่เพียงแต่ใช้งานได้ดี แต่ยังเต็มเปี่ยมไปด้วยประโยชน์ใช้สอย', en: 'This classic material is not only practical, it’s also extremely versatile.' }, image: 'zab27997-rgb' },
    ],
  },
]
