// Generated by scripts/build-content.mjs — do not edit by hand.
// Source: kohler.co.th colour and finish reference
// Harvested from /colorpalette and its seven children in both languages by scripts/harvest-content.mjs.
//
// Every field carries th and en. Images are lifestyle ids, resolved against
// lib/lifestyle.generated.ts — never remote URLs, so nothing can hotlink or
// upscale. `status` says what the source page actually holds:
//   'ok'   — real content
//   'stub' — the page exists and is empty at source
//   'gone' — the URL 404s at source

// นี่คือที่มาของ "สิบเอ็ดเฉด" ที่ทั้งเว็บนี้ใช้นำทาง — code ตรงกับรหัสเฉดใน
// lib/products.generated.ts (CP, BRD, AF, …) จึงเชื่อมสองชุดข้อมูลเข้าหากันได้
export type PaletteFinish = {
  /** รหัสเฉดของ Kohler เช่น CP, BN, 2MB — ว่างได้ถ้าหน้าไม่ได้ผูกไว้กับตัวกรอง */
  code: string
  title: { th: string; en: string }
  description: { th: string; en: string }
  searchUrl: string
  image: string | null
}

export type PaletteChild = {
  href: string
  heading: { th: string; en: string }
  blurb: { th: string; en: string }
  image: string | null
}

export type PaletteGroup = {
  slug: string
  path: string
  status: 'ok' | 'stub' | 'gone'
  title: { th: string; en: string }
  /** แผงสีของหน้าลูก — หน้าดัชนีไม่มี */
  finishes: PaletteFinish[]
  /** การ์ดพาไปหน้าลูก — มีเฉพาะหน้าดัชนี */
  children: PaletteChild[]
}

export const paletteGroups: PaletteGroup[] = [
  {
    slug: 'artist-editions-patterns',
    path: '/colorpalette/artist-editions-patterns.html',
    status: 'ok',
    title: { th: 'Artist Edition Patterns', en: 'ARTIST EDITIONS' },
    finishes: [
      {
        code: '',
        title: { th: 'Prairie Flowers™', en: 'Prairie Flowers™' },
        description: { th: '“Our ability to perceive quality in nature begins, as in art, with the pretty. It expands through successive stages of the beautiful to values as yet uncaptured by the language.” This quote from early 20th-century naturalist Aldo Leopold adorns the Prairie Flowers collection, transporting you to an untouched prairie where grass reaches high and flowers bloom with abandon. Prairie Flowers draws design inspiration from 18th-century dinnerware crafted for Catherine the Great of Russia.', en: '“Our ability to perceive quality in nature begins, as in art, with the pretty. It expands through successive stages of the beautiful to values as yet uncaptured by the language.” This quote from early 20th-century naturalist Aldo Leopold adorns the Prairie Flowers collection, transporting you to an untouched prairie where grass reaches high and flowers bloom with abandon. Prairie Flowers draws design inspiration from 18th-century dinnerware crafted for Catherine the Great of Russia.' },
        searchUrl: '',
        image: 'swatch-ae-wf',
      },
      {
        code: '',
        title: { th: 'English Trellis™', en: 'English Trellis™' },
        description: { th: 'In the early 17th century, Europeans revered intricate hand-painted or block-printed calico fabrics pieces, known as chintz, handcrafted in India. While it took European artists another century to learn the craft, they built on the rich tradition, adding their own interpretations of floral patterns. Inspired by this legacy, English Trellis presents delicate stems gracefully arching — as a vine climbs a garden trellis.', en: 'In the early 17th century, Europeans revered intricate hand-painted or block-printed calico fabrics pieces, known as chintz, handcrafted in India. While it took European artists another century to learn the craft, they built on the rich tradition, adding their own interpretations of floral patterns. Inspired by this legacy, English Trellis presents delicate stems gracefully arching — as a vine climbs a garden trellis.' },
        searchUrl: '',
        image: 'swatch-ae-fl',
      },
      {
        code: '',
        title: { th: 'Gilded Meadow™', en: 'Gilded Meadow™' },
        description: { th: 'In the early 17th century, Europeans revered intricate hand-painted or block-printed calico fabrics pieces, known as chintz, handcrafted in India. While it took European artists another century to learn the craft, they built on the rich tradition, adding their own interpretations of floral patterns. Inspired by this legacy, English Trellis presents delicate stems gracefully arching — as a vine climbs a garden trellis.', en: 'In the early 17th century, Europeans revered intricate hand-painted or block-printed calico fabrics pieces, known as chintz, handcrafted in India. While it took European artists another century to learn the craft, they built on the rich tradition, adding their own interpretations of floral patterns. Inspired by this legacy, English Trellis presents delicate stems gracefully arching — as a vine climbs a garden trellis.' },
        searchUrl: '',
        image: 'swatch-ae-gm',
      },
      {
        code: '',
        title: { th: 'Garden Bandana™', en: 'Garden Bandana™' },
        description: { th: 'Based on the pattern of a 16th-century porcelain dish from China’s Qing dynasty — a dish that regained popularity in 19th-century America, Garden Bandana features a pattern of blue chrysanthemums, peonies and foliage in reverse on a Biscuit-colored background. Inspired by centuries-old design, Garden Bandana feels remarkably contemporary.', en: 'Based on the pattern of a 16th-century porcelain dish from China’s Qing dynasty — a dish that regained popularity in 19th-century America, Garden Bandana features a pattern of blue chrysanthemums, peonies and foliage in reverse on a Biscuit-colored background. Inspired by centuries-old design, Garden Bandana feels remarkably contemporary.' },
        searchUrl: '',
        image: 'swatch-ae-gb-96',
      },
      {
        code: '',
        title: { th: 'Garden Bandana™', en: 'Garden Bandana™' },
        description: { th: 'Based on the pattern of a 16th-century porcelain dish from China’s Qing dynasty — a dish that regained popularity in 19th-century America, Garden Bandana features a pattern of red chrysanthemums, peonies and foliage in reverse on a Biscuit-colored background. Inspired by centuries-old design, Garden Bandana feels remarkably contemporary.', en: 'Based on the pattern of a 16th-century porcelain dish from China’s Qing dynasty — a dish that regained popularity in 19th-century America, Garden Bandana features a pattern of red chrysanthemums, peonies and foliage in reverse on a Biscuit-colored background. Inspired by centuries-old design, Garden Bandana feels remarkably contemporary.' },
        searchUrl: '',
        image: 'swatch-ae-g4-0',
      },
      {
        code: '',
        title: { th: 'Empress Bouquet™', en: 'Empress Bouquet™' },
        description: { th: 'The first people to develop printmaking, the Chinese have produced exceptional woodblock prints since the 9th century. Offering a modern interpretation of 18th-century Chinese print work, Empress Bouquet builds on this rich artistry with its floral motif and brilliant gold and metallic detailing. Each sink showcases a slightly different variation on the pattern, creating a one-of-a-kind piece.', en: 'The first people to develop printmaking, the Chinese have produced exceptional woodblock prints since the 9th century. Offering a modern interpretation of 18th-century Chinese print work, Empress Bouquet builds on this rich artistry with its floral motif and brilliant gold and metallic detailing. Each sink showcases a slightly different variation on the pattern, creating a one-of-a-kind piece.' },
        searchUrl: '',
        image: 'swatch-ae-smc',
      },
      {
        code: '',
        title: { th: 'Flight of Fancy™', en: 'Flight of Fancy™' },
        description: { th: 'Refined craftsmanship and intricate china patterns have held a place of honor in the dining room for centuries. Kohler brings this graceful look to the bathroom with Flight of Fancy. Featuring intricate, raised-enamel floral detailing framed by thin bands of rich gold or platinum, Flight of Fancy makes a stunning formal statement.', en: 'Refined craftsmanship and intricate china patterns have held a place of honor in the dining room for centuries. Kohler brings this graceful look to the bathroom with Flight of Fancy. Featuring intricate, raised-enamel floral detailing framed by thin bands of rich gold or platinum, Flight of Fancy makes a stunning formal statement.' },
        searchUrl: '',
        image: 'swatch-ae-fg',
      },
      {
        code: '',
        title: { th: 'Laureate™ - Gold', en: 'Laureate™ - Gold' },
        description: { th: 'The rich, warm glow of Polished Gold. With a choice of finishes, courtly Laureate brings refined elegance to the bathroom. Laureate combines acanthus leaves with a metalwork style used by the Ottoman Turks throughout the 18th century in embossed fabrics and as an architectural detail. Here the garland floral texture on White china creates an eye-catching juxtaposition.', en: 'The rich, warm glow of Polished Gold. With a choice of finishes, courtly Laureate brings refined elegance to the bathroom. Laureate combines acanthus leaves with a metalwork style used by the Ottoman Turks throughout the 18th century in embossed fabrics and as an architectural detail. Here the garland floral texture on White china creates an eye-catching juxtaposition.' },
        searchUrl: '',
        image: 'swatch-ae-pd',
      },
      {
        code: '',
        title: { th: 'Laureate™ - Polished Platinum', en: 'Laureate™ - Polished Platinum' },
        description: { th: 'The bright, reflective glint of Polished Platinum. With a choice of finishes, courtly Laureate brings refined elegance to the bathroom. Laureate combines acanthus leaves with a metalwork style used by the Ottoman Turks throughout the 18th century in embossed fabrics and as an architectural detail. Here the garland floral texture on White china creates an eye-catching juxtaposition.', en: 'The bright, reflective glint of Polished Platinum. With a choice of finishes, courtly Laureate brings refined elegance to the bathroom. Laureate combines acanthus leaves with a metalwork style used by the Ottoman Turks throughout the 18th century in embossed fabrics and as an architectural detail. Here the garland floral texture on White china creates an eye-catching juxtaposition.' },
        searchUrl: '',
        image: 'swatch-ae-pk',
      },
      {
        code: '',
        title: { th: 'Mica Gold™', en: 'Mica Gold™' },
        description: { th: 'More transparent than white and more glittering than gold, the special combination of a white basin with a gold edge presents the artistic concept of "more than a piece of art" with an incisive and vivid way, just to let you enjoy the best in luxury, elegance and beauty.', en: 'More transparent than white and more glittering than gold, the special combination of a white basin with a gold edge presents the artistic concept of "more than a piece of art" with an incisive and vivid way, just to let you enjoy the best in luxury, elegance and beauty.' },
        searchUrl: '',
        image: 'swatch-ae-pd',
      },
      {
        code: '',
        title: { th: 'Caravan™', en: 'Caravan™' },
        description: { th: 'Influenced by one of the oldest continuous civilizations, the Persia design reflects a rich tradition of culture and art. An eye-catching classic, Persia offers a fresh interpretation of Middle Eastern and Indian design traditions, drawing inspiration from decorative architecture and Moorish style. Organic, open line work contrasted with geometric patterns creates a unique juxtaposition and richness with Gold and Platinum micas. The White background creates an effective canvas for the pattern while offering ease of coordination with other fixtures in the space.', en: 'Influenced by one of the oldest continuous civilizations, the Persia design reflects a rich tradition of culture and art. An eye-catching classic, Persia offers a fresh interpretation of Middle Eastern and Indian design traditions, drawing inspiration from decorative architecture and Moorish style. Organic, open line work contrasted with geometric patterns creates a unique juxtaposition and richness with Gold and Platinum micas. The White background creates an effective canvas for the pattern while offering ease of coordination with other fixtures in the space.' },
        searchUrl: '',
        image: 'swatch-ae-sr2',
      },
      {
        code: '',
        title: { th: 'Nepal™', en: 'Nepal™' },
        description: { th: 'With a calming, Translucent Blue base and a contemplative pattern, the Nepal design transforms daily routines into moments of reflection. Inspired by East Indian traditions, it draws upon henna ceremonies and textile techniques. With delicate detailing and soft shifts in hue and finish, Nepal is ideal for the person desiring a peaceful escape.', en: 'With a calming, Translucent Blue base and a contemplative pattern, the Nepal design transforms daily routines into moments of reflection. Inspired by East Indian traditions, it draws upon henna ceremonies and textile techniques. With delicate detailing and soft shifts in hue and finish, Nepal is ideal for the person desiring a peaceful escape.' },
        searchUrl: '',
        image: 'swatch-ae-sr1',
      },
      {
        code: '',
        title: { th: 'Serperntine Bronze™', en: 'Serperntine Bronze™' },
        description: { th: 'A Chinese bronze basin dating from 475 to 221 B.C. and featuring turtles, fish and intertwining serpents serves as the inspiration for Serpentine Bronze — a sink coveted for its warm, harmonious colors. At first glance, the sink appears covered with an interesting scroll pattern, yet a closer look reveals the surprising, exotic serpentine heads. The matte and glossy surface on a Sandbar background gives this fresh design an aged appearance.', en: 'A Chinese bronze basin dating from 475 to 221 B.C. and featuring turtles, fish and intertwining serpents serves as the inspiration for Serpentine Bronze — a sink coveted for its warm, harmonious colors. At first glance, the sink appears covered with an interesting scroll pattern, yet a closer look reveals the surprising, exotic serpentine heads. The matte and glossy surface on a Sandbar background gives this fresh design an aged appearance.' },
        searchUrl: '',
        image: 'swatch-ae-sp',
      },
      {
        code: '',
        title: { th: 'Imperial Blue™', en: 'Imperial Blue™' },
        description: { th: 'With intricate detail, a serpentine dragon encircles the bowl of this vessel, tail in hand to form a curvaceous loop. Typical of the Yongle reign of the Ming dynasty but later copied by imperial artisans, the blue-and-white floral pattern and dragon portray traditional strength and wisdom. Imperial Blue draws inspiration from a porcelain vase created during this period.', en: 'With intricate detail, a serpentine dragon encircles the bowl of this vessel, tail in hand to form a curvaceous loop. Typical of the Yongle reign of the Ming dynasty but later copied by imperial artisans, the blue-and-white floral pattern and dragon portray traditional strength and wisdom. Imperial Blue draws inspiration from a porcelain vase created during this period.' },
        searchUrl: '',
        image: 'swatch-ae-vb',
      },
      {
        code: '',
        title: { th: 'Bourbon Rutile', en: 'Bourbon Rutile' },
        description: { th: 'Inspired by studio pottery, the Derring collection celebrates the inherent beauty and authenticity of handcrafted ceramics. Each sink is a one-of-a-kind creation, finished with unique rutile and artisanal glazes that produce fascinating surface effects. A handcarved texture accentuates the subtle tonal variations. Featured in neutral hues, this sink can be the centerpiece of your bath, or it can serve as a unifying element that pulls everything else together.', en: 'Inspired by studio pottery, the Derring collection celebrates the inherent beauty and authenticity of handcrafted ceramics. Each sink is a one-of-a-kind creation, finished with unique rutile and artisanal glazes that produce fascinating surface effects. A handcarved texture accentuates the subtle tonal variations. Featured in neutral hues, this sink can be the centerpiece of your bath, or it can serve as a unifying element that pulls everything else together.' },
        searchUrl: '',
        image: 'swatch-rb2',
      },
    ],
    children: [

    ],
  },
  {
    slug: 'bathroom-colors',
    path: '/colorpalette/bathroom-colors.html',
    status: 'ok',
    title: { th: 'Bathroom Lavatory Colors', en: 'Bathroom Lavatory Colors' },
    finishes: [
      {
        code: '0',
        title: { th: 'Kohler White', en: 'Kohler White' },
        description: { th: 'Clean and crisp, it is a perfect fit for any style. Can work in traditional or contemporary settings, and allow total freedom in decorating.', en: 'Clean and crisp, it is a perfect fit for any style. Can work in traditional or contemporary settings, and allow total freedom in decorating.' },
        searchUrl: '/results/Categories/lavatories?search=0',
        image: 'swatch-0',
      },
      {
        code: '0',
        title: { th: 'Jacob Delafon White', en: 'Jacob Delafon White' },
        description: { th: 'Clean and crisp, it is a perfect fit for any style. Can work in traditional or contemporary settings, and allow total freedom in decorating.', en: 'Clean and crisp, it is a perfect fit for any style. Can work in traditional or contemporary settings, and allow total freedom in decorating.' },
        searchUrl: '/results/Categories/lavatories?search=0',
        image: 'swatch-0',
      },
      {
        code: 'HW1',
        title: { th: 'Honed White', en: 'Honed White' },
        description: { th: '"Inspired by nature with a perfect balance of bold and sensual, KOHLER Honed White offers new possibilities in bath décor. Like stone that has been smoothed and softened by time, Honed White places enduring warmth and sophistication at your fingertips. "', en: '"Inspired by nature with a perfect balance of bold and sensual, KOHLER Honed White offers new possibilities in bath décor. Like stone that has been smoothed and softened by time, Honed White places enduring warmth and sophistication at your fingertips. "' },
        searchUrl: '/results/Categories/lavatories?search=HW1',
        image: 'swatch-hw1',
      },
      {
        code: 'G81',
        title: { th: 'White Impressions', en: 'White Impressions' },
        description: { th: 'White Impressions', en: 'White Impressions' },
        searchUrl: '/results/Categories/lavatories?search=G81',
        image: 'swatch-g81',
      },
      {
        code: '7',
        title: { th: 'Black Black™', en: 'Black Black™' },
        description: { th: 'A classic color that acts as the foundation in the kitchen or bath. It is traditional and elegant but can also work in contemporary settings as well.', en: 'A classic color that acts as the foundation in the kitchen or bath. It is traditional and elegant but can also work in contemporary settings as well.' },
        searchUrl: '/results/Categories/lavatories?search=7',
        image: 'swatch-7',
      },
      {
        code: 'HB1',
        title: { th: 'Honed Black', en: 'Honed Black' },
        description: { th: 'Honed Black', en: 'Honed Black' },
        searchUrl: '/results/Categories/lavatories?search=HB1',
        image: 'swatch-hb1',
      },
      {
        code: '0',
        title: { th: 'Kohler White', en: 'Kohler White' },
        description: { th: 'Clean and crisp, it is a perfect fit for any style. Can work in traditional or contemporary settings, and allow total freedom in decorating.', en: 'Clean and crisp, it is a perfect fit for any style. Can work in traditional or contemporary settings, and allow total freedom in decorating.' },
        searchUrl: '/results/Categories/toilets?search=0',
        image: 'swatch-0',
      },
      {
        code: '0',
        title: { th: 'Kohler White', en: 'Kohler White' },
        description: { th: 'Clean and crisp, it is a perfect fit for any style. Can work in traditional or contemporary settings, and allow total freedom in decorating.', en: 'Clean and crisp, it is a perfect fit for any style. Can work in traditional or contemporary settings, and allow total freedom in decorating.' },
        searchUrl: '/results/Categories/bathing?search=0',
        image: 'swatch-0',
      },
      {
        code: 'C36',
        title: { th: 'Ebony', en: 'Ebony' },
        description: { th: 'Ebony', en: 'Ebony' },
        searchUrl: '/results/Categories/bathing?search=C36',
        image: 'swatch-1wp',
      },
      {
        code: 'C38',
        title: { th: 'Clear Oak', en: 'Clear Oak' },
        description: { th: 'Clear Oak', en: 'Clear Oak' },
        searchUrl: '/results/Categories/bathing?search=C38',
        image: 'swatch-1wn',
      },
      {
        code: 'E63',
        title: { th: 'Walnut', en: 'Walnut' },
        description: { th: 'Walnut', en: 'Walnut' },
        searchUrl: '/results/Categories/bathing?search=E63',
        image: 'swatch-1wm',
      },
      {
        code: 'CP',
        title: { th: 'Polished Chrome', en: 'Polished Chrome' },
        description: { th: 'Polished Chrome coordinates beautifully with a wide variety of fixture styles and types of décor. It works particularly well for evoking a nostalgic look, as in a 1920s- or other vintage-style bath, but also complements contemporary styles.', en: 'Polished Chrome coordinates beautifully with a wide variety of fixture styles and types of décor. It works particularly well for evoking a nostalgic look, as in a 1920s- or other vintage-style bath, but also complements contemporary styles.' },
        searchUrl: '/results/Categories/bathroom-showering?search=CP',
        image: 'swatch-cp',
      },
      {
        code: 'SN',
        title: { th: 'Vibrant® Polished Nickel', en: 'Vibrant® Polished Nickel' },
        description: { th: 'Shiny like chrome, Vibrant Polished Nickel can be used in almost any style of décor and is a favorite of many designers. A sophisticated look that works well with both traditional and contemporary styles, it can add an elegant touch to any bathroom.', en: 'Shiny like chrome, Vibrant Polished Nickel can be used in almost any style of décor and is a favorite of many designers. A sophisticated look that works well with both traditional and contemporary styles, it can add an elegant touch to any bathroom.' },
        searchUrl: '/results/Categories/bathroom-showering?search=SN',
        image: 'swatch-sn',
      },
      {
        code: '2BZ',
        title: { th: 'Oil-Rubbed Bronze', en: 'Oil-Rubbed Bronze' },
        description: { th: 'Oil-Rubbed Bronze', en: 'Oil-Rubbed Bronze' },
        searchUrl: '/results/Categories/bathroom-showering?search=2BZ',
        image: 'swatch-2bz',
      },
      {
        code: '0',
        title: { th: 'White', en: 'White' },
        description: { th: 'Clean and crisp, it is a perfect fit for any style. Can work in traditional or contemporary settings, and allow total freedom in decorating.', en: 'Clean and crisp, it is a perfect fit for any style. Can work in traditional or contemporary settings, and allow total freedom in decorating.' },
        searchUrl: '/results/Categories/bathroom-showering?search=0',
        image: 'swatch-0',
      },
      {
        code: '7',
        title: { th: 'Black Black™', en: 'Black Black™' },
        description: { th: 'A classic color that acts as the foundation in the kitchen or bath. It is traditional and elegant but can also work in contemporary settings as well.', en: 'A classic color that acts as the foundation in the kitchen or bath. It is traditional and elegant but can also work in contemporary settings as well.' },
        searchUrl: '/results/Categories/bathroom-showering?search=7',
        image: 'swatch-7',
      },
      {
        code: 'FGN',
        title: { th: 'Chartreuse', en: 'Chartreuse' },
        description: { th: 'Chartreuse', en: 'Chartreuse' },
        searchUrl: '/results/Categories/bathroom-showering?search=FGN',
        image: 'swatch-fgn',
      },
      {
        code: 'FRD',
        title: { th: 'Cherry Red', en: 'Cherry Red' },
        description: { th: 'Cherry Red', en: 'Cherry Red' },
        searchUrl: '/results/Categories/bathroom-showering?search=FRD',
        image: 'swatch-frd',
      },
      {
        code: 'CP',
        title: { th: 'Polished Chrome', en: 'Polished Chrome' },
        description: { th: 'Polished Chrome coordinates beautifully with a wide variety of fixture styles and types of décor. It works particularly well for evoking a nostalgic look, as in a 1920s- or other vintage-style bath, but also complements contemporary styles.', en: 'Polished Chrome coordinates beautifully with a wide variety of fixture styles and types of décor. It works particularly well for evoking a nostalgic look, as in a 1920s- or other vintage-style bath, but also complements contemporary styles.' },
        searchUrl: '/results/Categories/bathroom-accessories?search=CP',
        image: 'swatch-cp',
      },
      {
        code: '2BZ',
        title: { th: 'Oil-Rubbed Bronze', en: 'Oil-Rubbed Bronze' },
        description: { th: 'Oil-Rubbed Bronze', en: 'Oil-Rubbed Bronze' },
        searchUrl: '/results/Categories/bathroom-accessories?search=2BZ',
        image: 'swatch-2bz',
      },
      {
        code: 'BS',
        title: { th: 'Brushed Stainless', en: 'Brushed Stainless' },
        description: { th: 'Brushed Stainless', en: 'Brushed Stainless' },
        searchUrl: '/results/Categories/bathroom-accessories?search=BS',
        image: 'swatch-bs',
      },
      {
        code: 'S',
        title: { th: 'Stainless', en: 'Stainless' },
        description: { th: 'Stainless', en: 'Stainless' },
        searchUrl: '/results/Categories/bathroom-accessories?search=S',
        image: 'swatch-s',
      },
    ],
    children: [

    ],
  },
  {
    slug: 'bathroom-faucet-finishes',
    path: '/colorpalette/bathroom-faucet-finishes.html',
    status: 'ok',
    title: { th: 'Faucet Finishes', en: 'Faucet Finishes' },
    finishes: [
      {
        code: 'CP',
        title: { th: 'Polished Chrome', en: 'Polished Chrome' },
        description: { th: 'Polished Chrome coordinates beautifully with a wide variety of fixture styles and types of décor. It works particularly well for evoking a nostalgic look, as in a 1920s- or other vintage-style bath, but also complements contemporary styles.', en: 'Polished Chrome coordinates beautifully with a wide variety of fixture styles and types of décor. It works particularly well for evoking a nostalgic look, as in a 1920s- or other vintage-style bath, but also complements contemporary styles.' },
        searchUrl: '/results/Categories/bathroom-faucets?search=CP',
        image: 'swatch-cp',
      },
      {
        code: '2BZ',
        title: { th: 'Oil-Rubbed Bronze', en: 'Oil-Rubbed Bronze' },
        description: { th: 'Oil-Rubbed Bronze', en: 'Oil-Rubbed Bronze' },
        searchUrl: '/results/Categories/bathroom-faucets?search=2BZ',
        image: 'swatch-2bz',
      },
      {
        code: '0',
        title: { th: 'White', en: 'White' },
        description: { th: 'Clean and crisp, it is a perfect fit for any style. Can work in traditional or contemporary settings, and allow total freedom in decorating.', en: 'Clean and crisp, it is a perfect fit for any style. Can work in traditional or contemporary settings, and allow total freedom in decorating.' },
        searchUrl: '/results/Categories/bathroom-faucets?search=0',
        image: 'swatch-0',
      },
      {
        code: '96',
        title: { th: 'Biscuit', en: 'Biscuit' },
        description: { th: 'A classic, creamy shade with just a hint of yellow. This very soft color is at home with contemporary as well as traditional and country settings. It accents glowing earth tones and complements nearly every color in the Kohler palette.', en: 'A classic, creamy shade with just a hint of yellow. This very soft color is at home with contemporary as well as traditional and country settings. It accents glowing earth tones and complements nearly every color in the Kohler palette.' },
        searchUrl: '/results/Categories/bathroom-faucets?search=96',
        image: 'swatch-96',
      },
    ],
    children: [

    ],
  },
  {
    slug: 'bathroom-furniture-colors',
    path: '/colorpalette/bathroom-furniture-colors.html',
    status: 'ok',
    title: { th: 'Bathroom Furniture Colors', en: 'Bathroom Furniture Colors' },
    finishes: [
      {
        code: '0',
        title: { th: 'Kohler White', en: 'Kohler White' },
        description: { th: 'Clean and crisp, it is a perfect fit for any style. Can work in traditional or contemporary settings, and allow total freedom in decorating.', en: 'Clean and crisp, it is a perfect fit for any style. Can work in traditional or contemporary settings, and allow total freedom in decorating.' },
        searchUrl: '/results/Categories/bathroom-furniture?search=0',
        image: 'swatch-0',
      },
      {
        code: 'HW1',
        title: { th: 'Honed White', en: 'Honed White' },
        description: { th: 'Inspired by nature with a perfect balance of bold and sensual, KOHLER Honed White offers new possibilities in bath décor. Like stone that has been smoothed and softened by time, Honed White places enduring warmth and sophistication at your fingertips.', en: 'Inspired by nature with a perfect balance of bold and sensual, KOHLER Honed White offers new possibilities in bath décor. Like stone that has been smoothed and softened by time, Honed White places enduring warmth and sophistication at your fingertips.' },
        searchUrl: '/results/Categories/bathroom-furniture?search=HW1',
        image: 'swatch-hw1',
      },
      {
        code: 'F02',
        title: { th: 'Bathroom Furniture Color', en: 'Bathroom Furniture Color' },
        description: { th: 'Bathroom Furniture Color', en: 'Bathroom Furniture Color' },
        searchUrl: '/results/Categories/bathroom-furniture?search=F02',
        image: 'swatch-f5',
      },
      {
        code: 'GLG',
        title: { th: 'Gray', en: 'Gray' },
        description: { th: 'Gray', en: 'Gray' },
        searchUrl: '/results/Categories/bathroom-furniture?search=GLG',
        image: 'swatch-g88',
      },
      {
        code: 'GLW',
        title: { th: 'Glossy White', en: 'Glossy White' },
        description: { th: 'Glossy White', en: 'Glossy White' },
        searchUrl: '/results/Categories/bathroom-furniture?search=GLW',
        image: 'swatch-1wa',
      },
      {
        code: 'DBC',
        title: { th: 'Cherry', en: 'Cherry' },
        description: { th: 'Cherry', en: 'Cherry' },
        searchUrl: '/results/Categories/bathroom-furniture?search=DBC',
        image: 'swatch-1wg',
      },
      {
        code: 'F2',
        title: { th: 'Black Forest', en: 'Black Forest' },
        description: { th: 'Black Forest', en: 'Black Forest' },
        searchUrl: '/results/Categories/bathroom-furniture?search=F2',
        image: 'swatch-f2',
      },
      {
        code: 'F69',
        title: { th: 'Woodland', en: 'Woodland' },
        description: { th: 'Woodland', en: 'Woodland' },
        searchUrl: '/results/Categories/bathroom-furniture?search=F69',
        image: 'swatch-f69',
      },
      {
        code: 'ST',
        title: { th: 'Stainless Steel', en: 'Stainless Steel' },
        description: { th: 'Elegant and versatile, Stainless Steel finish complements both cool and warm tones and brings distinction to any home décor.', en: 'Elegant and versatile, Stainless Steel finish complements both cool and warm tones and brings distinction to any home décor.' },
        searchUrl: '/results/Categories/bathroom-furniture?search=ST',
        image: 'swatch-st',
      },
      {
        code: 'ST',
        title: { th: 'Stainless Steel', en: 'Stainless Steel' },
        description: { th: 'Elegant and versatile, Stainless Steel finish complements both cool and warm tones and brings distinction to any home décor.', en: 'Elegant and versatile, Stainless Steel finish complements both cool and warm tones and brings distinction to any home décor.' },
        searchUrl: '/results/Categories/cabinets?search=ST',
        image: 'swatch-st',
      },
      {
        code: '0',
        title: { th: 'Kohler White', en: 'Kohler White' },
        description: { th: 'Clean and crisp, it is a perfect fit for any style. Can work in traditional or contemporary settings, and allow total freedom in decorating.', en: 'Clean and crisp, it is a perfect fit for any style. Can work in traditional or contemporary settings, and allow total freedom in decorating.' },
        searchUrl: '/results/Categories/cabinets?search=0',
        image: 'swatch-0',
      },
      {
        code: 'DBC',
        title: { th: 'Cherry', en: 'Cherry' },
        description: { th: 'Cherry', en: 'Cherry' },
        searchUrl: '/results/Categories/cabinets?search=DBC',
        image: 'swatch-1wg',
      },
      {
        code: 'F02',
        title: { th: 'Bathroom Furniture Color', en: 'Bathroom Furniture Color' },
        description: { th: 'Bathroom Furniture Color', en: 'Bathroom Furniture Color' },
        searchUrl: '/results/Categories/cabinets?search=F02',
        image: 'swatch-f5',
      },
      {
        code: 'F69',
        title: { th: 'Woodland', en: 'Woodland' },
        description: { th: 'Woodland', en: 'Woodland' },
        searchUrl: '/results/Categories/cabinets?search=F69',
        image: 'swatch-f69',
      },
    ],
    children: [

    ],
  },
  {
    slug: 'commercial-finishes',
    path: '/colorpalette/commercial-finishes.html',
    status: 'ok',
    title: { th: 'Sensor Faucet Finishes', en: 'Sensor Faucet Finishes' },
    finishes: [
      {
        code: 'CP',
        title: { th: 'Polished Chrome', en: 'Polished Chrome' },
        description: { th: 'Polished Chrome coordinates beautifully with a wide variety of fixture styles and types of décor. It works particularly well for evoking a nostalgic look, as in a 1920s- or other vintage-style bath, but also complements contemporary styles.', en: 'Polished Chrome coordinates beautifully with a wide variety of fixture styles and types of décor. It works particularly well for evoking a nostalgic look, as in a 1920s- or other vintage-style bath, but also complements contemporary styles.' },
        searchUrl: '/results/Categories/commercial-bathroom?search=CP',
        image: 'swatch-cp',
      },
      {
        code: '2BN',
        title: { th: 'Oil-Rubbed Bronze', en: 'Oil-Rubbed Bronze' },
        description: { th: 'Oil-Rubbed Bronze', en: 'Oil-Rubbed Bronze' },
        searchUrl: '/results/Categories/commercial-bathroom?search=2BN',
        image: 'swatch-2bz',
      },
    ],
    children: [

    ],
  },
  {
    slug: 'index',
    path: '/colorpalette',
    status: 'ok',
    title: { th: 'Bathroom', en: 'Bathroom' },
    finishes: [

    ],
    children: [
      { href: '/colorpalette/bathroom-colors.html', heading: { th: 'Bathroom Colors', en: 'Bathroom Colors' }, blurb: { th: 'Explore the colors.', en: 'Explore the colors.' }, image: 'zab59846-rgb' },
      { href: '/colorpalette/bathroom-furniture-colors.html', heading: { th: 'Bathroom Furniture Colors', en: 'Bathroom Furniture Colors' }, blurb: { th: 'Explore the colors.', en: 'Explore the colors.' }, image: 'zab69059-rgb' },
      { href: '/colorpalette/bathroom-faucet-finishes.html', heading: { th: 'Bathroom Faucet Finishes', en: 'Bathroom Faucet Finishes' }, blurb: { th: 'Explore the colors.', en: 'Explore the colors.' }, image: 'zab82187-rgb' },
      { href: '/colorpalette/artist-editions-patterns.html', heading: { th: 'Artist Editions Patterns', en: 'Artist Edition Patterns' }, blurb: { th: 'Explore the patterns.', en: 'Explore the patterns.' }, image: 'zab83805-rgb' },
      { href: '/colorpalette/commercial-finishes.html', heading: { th: 'Commercial Finishes', en: 'Commercial Finishes' }, blurb: { th: 'Explore the colors.', en: 'Explore the colors.' }, image: 'zaa38095-1800x800' },
      { href: '/colorpalette/kitchen-sink-colors.html', heading: { th: 'Kitchen Sink Colors', en: 'Kitchen Sink Colors' }, blurb: { th: 'Explore the colors.', en: 'Explore the colors.' }, image: 'zab64194-rgb' },
      { href: '/colorpalette/kitchen-faucet-finishes.html', heading: { th: 'Kitchen Faucet Finishes', en: 'Kitchen Faucet Finishes' }, blurb: { th: 'Explore the colors.', en: 'Explore the colors.' }, image: 'zab86025-rgb' },
    ],
  },
  {
    slug: 'kitchen-faucet-finishes',
    path: '/colorpalette/kitchen-faucet-finishes.html',
    status: 'ok',
    title: { th: 'Kitchen Faucet Finishes', en: 'Kitchen Faucet Finishes' },
    finishes: [
      {
        code: 'CP',
        title: { th: 'Polished Chrome', en: 'Polished Chrome' },
        description: { th: 'Polished chrome coordinates beautifully with a wide variety of fixture styles and types of décor. It works particularly well for evoking a nostalgic look, as in a 1920s- or other vintage-style bath, but also complements contemporary styles.', en: 'Polished chrome coordinates beautifully with a wide variety of fixture styles and types of décor. It works particularly well for evoking a nostalgic look, as in a 1920s- or other vintage-style bath, but also complements contemporary styles.' },
        searchUrl: '/results/Categories/kitchen-faucets?search=CP',
        image: 'swatch-cp',
      },
    ],
    children: [

    ],
  },
  {
    slug: 'kitchen-sink-colors',
    path: '/colorpalette/kitchen-sink-colors.html',
    status: 'ok',
    title: { th: 'Kitchen Sinks', en: 'Kitchen Sinks' },
    finishes: [
      {
        code: 'ST',
        title: { th: 'Stainless Steel', en: 'Stainless Steel' },
        description: { th: 'Elegant and versatile, Stainless Steel finish complements both cool and warm tones and brings distinction to any home décor.', en: 'Elegant and versatile, Stainless Steel finish complements both cool and warm tones and brings distinction to any home décor.' },
        searchUrl: '/results/Categories/kitchen-sinks?search=ST',
        image: 'swatch-st',
      },
    ],
    children: [

    ],
  },
]

export const getPaletteGroup = (slug: string): PaletteGroup | undefined =>
  paletteGroups.find((g) => g.slug === slug)
