// Generated by scripts/build-editorial.mjs from a crawl of kohler.co.th.
// Do not edit by hand — re-run the two scripts instead:
//   node scripts/scrape-editorial.mjs <report.json>
//   node scripts/build-editorial.mjs  <report.json>
//
// THE TEXT HERE IS KOHLER'S. Titles, paragraphs and image alt strings are
// copied verbatim from their article pages; the excerpt is the first sentence
// of the article, cut at a word boundary. We wrote none of it and translated
// none of it. Same licensing position as the product photography and the
// lifestyle library: fine for a prototype shown to the brand it belongs to,
// not fine to publish. `source.url` on every post keeps the origin attached.
//
// Two fields are ours rather than Kohler's, and both are marked below: `tag`,
// derived from which hub page linked the article, and `captured`, the day we
// crawled. Kohler's article template publishes no category and no date — their
// sitemap stamps every URL with the time of the request, so there is no real
// publication date to read. Nothing here invents one.

export type PostImage = {
  /** largest rendition on disk */
  src: string;
  /** smallest rendition on disk — same pixels when only one exists */
  srcSmall: string;
  width: number;
  height: number;
  /** Kohler's own alt text, or the article title where they left it empty */
  alt: string;
};

export type PostVideo = {
  /** YouTube id. Nothing is requested from YouTube until the reader clicks. */
  id: string;
  /** the title Kohler published it under, via oEmbed — the play button's name */
  title: string;
  /** poster frame, downloaded and re-served from our own origin */
  poster: PostImage | null;
};

export type Post = {
  slug: string;
  /**
   * Kohler's headline. Their Thai site publishes one language per article, so
   * `en` carries the same string rather than a translation we invented — the
   * fallback shape the rest of lib/i18n.ts already uses.
   */
  title: { th: string; en: string };
  /** first sentence of the article, cut at a word boundary */
  excerpt: { th: string; en: string };
  /**
   * OURS — the day this was crawled, NOT a publication date.
   *
   * Kohler's article template carries no date in the markup, no JSON-LD
   * datePublished and no visible byline, and their sitemap stamps every URL
   * with the time of the request, so there is nothing real to read. Every post
   * therefore shares one date. components/ArticlesContent and ArticleContent
   * show the source instead; anything that still prints this will print the
   * same day on every card, which is the honest outcome of having no date
   * rather than a bug to work around by inventing ten.
   */
  date: string;
  /** OURS — derived from the hub page that linked the article */
  tag: string;
  tagEn: string;
  /** bath or kitchen, from the same hub signal as `tag` */
  space: 'bath' | 'kitchen';
  /**
   * OURS — id into lib/lifestyle.generated.ts, kept for components/home, which
   * renders its article cards with a room photograph rather than the article's
   * own picture. The article's real imagery is `cover`/`hero`/`figures`.
   */
  coverId: string;
  source: { url: string; route: string };
  hero: PostImage;
  /** the article's own card image — Kohler's, unlike `coverId` */
  cover: PostImage;
  figures: PostImage[];
  body: string[];
  /** no English edition exists; declared so a translator can fill it later */
  bodyEn?: string[];
  /** only the ids that are still playable — see the note in the build script */
  videos: PostVideo[];
  /** set when the video is the article's opening slot rather than an inline one */
  bannerVideo: string | null;
};

/** OURS — the day this catalogue was crawled, not a publication date. */
export const CAPTURED = "2026-09-02";

export const posts: Post[] = [
  {
    slug: "the-finish-is-just-the-beginning",
    title: { th: "สีสันเป็นเพียงแค่จุดเริ่มต้น", en: "สีสันเป็นเพียงแค่จุดเริ่มต้น" },
    excerpt: { th: "มีหลากหลายวิธีในการออกแบบห้องครัวหรือห้องน้ำของคุณ คุณอาจจะเริ่มต้นด้วยสไตล์ที่คุณชื่นชอบหรือเลือกผลิตภัณฑ์โปรด คุณอาจจะพิจารณาสีผนังหรือกระเบื้อง…", en: "มีหลากหลายวิธีในการออกแบบห้องครัวหรือห้องน้ำของคุณ คุณอาจจะเริ่มต้นด้วยสไตล์ที่คุณชื่นชอบหรือเลือกผลิตภัณฑ์โปรด คุณอาจจะพิจารณาสีผนังหรือกระเบื้อง…" },
    date: CAPTURED,
    tag: "เรื่องเล่าจาก KOHLER",
    tagEn: "From KOHLER",
    space: "bath",
    coverId: "aaa68094-rgb",
    source: { url: "https://www.kohler.co.th/articles/the-finish-is-just-the-beginning.html", route: "/articles/the-finish-is-just-the-beginning.html" },
    hero: { src: "/lifestyle/editorial/the-finish-is-just-the-beginning-hero-1800.webp", srcSmall: "/lifestyle/editorial/the-finish-is-just-the-beginning-hero-900.webp", width: 1800, height: 2227, alt: "สีสันเป็นเพียงแค่จุดเริ่มต้น" },
    cover: { src: "/lifestyle/editorial/the-finish-is-just-the-beginning-fig1-1800.webp", srcSmall: "/lifestyle/editorial/the-finish-is-just-the-beginning-fig1-900.webp", width: 1800, height: 422, alt: "Vibrant® ไทเทเนียม (TT)" },
    figures: [
      { src: "/lifestyle/editorial/the-finish-is-just-the-beginning-fig1-1800.webp", srcSmall: "/lifestyle/editorial/the-finish-is-just-the-beginning-fig1-900.webp", width: 1800, height: 422, alt: "Vibrant® ไทเทเนียม (TT)" },
      { src: "/lifestyle/editorial/the-finish-is-just-the-beginning-fig2-1800.webp", srcSmall: "/lifestyle/editorial/the-finish-is-just-the-beginning-fig2-900.webp", width: 1800, height: 422, alt: "วินเทจนิกเกิล (VNT)" },
      { src: "/lifestyle/editorial/the-finish-is-just-the-beginning-fig3-1800.webp", srcSmall: "/lifestyle/editorial/the-finish-is-just-the-beginning-fig3-900.webp", width: 1800, height: 422, alt: "สีดำด้าน (BL)" },
    ],
    body: [
      "มีหลากหลายวิธีในการออกแบบห้องครัวหรือห้องน้ำของคุณ คุณอาจจะเริ่มต้นด้วยสไตล์ที่คุณชื่นชอบหรือเลือกผลิตภัณฑ์โปรด คุณอาจจะพิจารณาสีผนังหรือกระเบื้อง แทนที่จะกังวลใจว่าอะไรเหมาะหรือไม่เหมาะ คุณควรเริ่มด้วยการเลือกผลิตภัณฑ์ที่คุณชอบมากก่อนแล้วจับคู่กับก๊อกน้ำที่สวยสมบูรณ์แบบ หลังจากนั้นจัดแต่งให้ทุกอย่างดูลงตัวในแบบฉบับของคุณ เรียนรู้เพิ่มเติมเกี่ยวกับผลิตภัณฑ์ของเราที่จะช่วยสะท้อนความเป็นคุณออกมาได้อย่างชัดเจน.",
      "ความชื่นชอบในเรื่องของโทนสีเป็นความชอบเฉพาะบุคคล บางทีไทเทเนียมอันโดดเด่น หรือนิกเกิลเงาวาวที่ดูอบอุ่นอาจสื่อถึงคุณ สำรวจก๊อกน้ำของเราเพื่อค้นหาแบบที่เข้ากับบุคลิกและสไตล์ของคุณ.",
      "พื้นผิวเคลือบ Vibrant® PVD เป็นการผลิตที่ทันสมัย โดยเทคโนโลยีการเปลี่ยนสสารให้เป็นไอระเหย (PVD) และเคลือบลงพื้นผิวผลิตภัณฑ์เพื่อสะท้อนความสง่างาม โดยพื้นฐาน PVD คือเทคนิคการเคลือบด้วยละอองโดยการถ่ายเทสสารระดับอะตอม ในระหว่างกระบวนการนี้ ไอระเหยจะควบแน่นลงบนผิวผลิตภัณฑ์และสร้างแผ่นฟิล์มบางๆ กลายเป็นพื้นผิวเคลือบสี.",
      "เพื่อช่วยคุณสร้างสรรค์รูปลักษณ์สำหรับห้องครัวหรือห้องน้ำอย่างสมบูรณ์ เราขอเสนอผลิตภัณฑ์พื้นผิวเคลือบหลากหลายแบบที่เข้ากันได้ดีกับทุกผลิตภัณฑ์",
      "พื้นผิวเคลือบสีเทาเข้มที่เงาวาวเหมาะสมลงตัวกับห้องโทนสีเข้ม หรือธีมสีเดียว",
      "พื้นผิวสีเข้มที่ทำให้เกิดความโดดเด่นในห้องทุกสไตล์",
      "พื้นผิวเคลือบที่ดูสะอาดตาซ่อนความอบอุ่นที่ละเอียดสุขุมโดยไม่ก่อให้เกิดความรู้สึกจริงจังมากเกินไป",
      "ลึกซึ้งและซับซ้อนตามธรรมชาติ Vibrant® สีทองคำปัดลายแบบใหม่เป็นแรงบันดาลใจที่สะท้อนถึงการคิดตรึกตรองมาเป็นอย่างดี (*ไม่มีเนื้อทอง)",
      "พื้นผิวเคลือบเรียบลื่นที่เข้าคู่กันกับเครื่องใช้ทันสมัยและสไตล์ก๊อกน้ำหลายแบบ",
      "เพื่อให้แน่ใจว่าคุณพึงพอใจที่สุด ก๊อกน้ำเคลือบเงา KOHLER มีการรับประกันสินค้าภายใต้เงื่อนไขข้อกำหนดของบริษัทฯ",
    ],
    videos: [],
    bannerVideo: null,
  },
  {
    slug: "intelligent-toilet",
    title: { th: "KOHLER ® Intelligent Toilets", en: "KOHLER ® Intelligent Toilets" },
    excerpt: { th: "การเลือกใช้สุขภัณฑ์อัจฉริยะจากโคห์เลอร์ คือการยืนยันว่ารายละเอียดเป็นสิ่งสำคัญที่สุดสำหรับคุณ ด้วยนวัตกรรมเหนือชั้นผสานงานดีไซน์อย่างยากจะหาใครเทียบ…", en: "การเลือกใช้สุขภัณฑ์อัจฉริยะจากโคห์เลอร์ คือการยืนยันว่ารายละเอียดเป็นสิ่งสำคัญที่สุดสำหรับคุณ ด้วยนวัตกรรมเหนือชั้นผสานงานดีไซน์อย่างยากจะหาใครเทียบ…" },
    date: CAPTURED,
    tag: "เรื่องเล่าจาก KOHLER",
    tagEn: "From KOHLER",
    space: "bath",
    coverId: "aab15367-rgb",
    source: { url: "https://www.kohler.co.th/articles/intelligent-toilet.html", route: "/articles/intelligent-toilet.html" },
    hero: { src: "/lifestyle/editorial/intelligent-toilet-hero-1800.webp", srcSmall: "/lifestyle/editorial/intelligent-toilet-hero-900.webp", width: 1800, height: 532, alt: "KOHLER ® Intelligent Toilets" },
    cover: { src: "/lifestyle/editorial/intelligent-toilet-fig1-1800.webp", srcSmall: "/lifestyle/editorial/intelligent-toilet-fig1-900.webp", width: 1800, height: 532, alt: "ดีไซน์" },
    figures: [
      { src: "/lifestyle/editorial/intelligent-toilet-fig1-1800.webp", srcSmall: "/lifestyle/editorial/intelligent-toilet-fig1-900.webp", width: 1800, height: 532, alt: "ดีไซน์" },
      { src: "/lifestyle/editorial/intelligent-toilet-fig2-1800.webp", srcSmall: "/lifestyle/editorial/intelligent-toilet-fig2-900.webp", width: 1800, height: 532, alt: "ความสะอาด" },
      { src: "/lifestyle/editorial/intelligent-toilet-fig3-1800.webp", srcSmall: "/lifestyle/editorial/intelligent-toilet-fig3-900.webp", width: 1800, height: 533, alt: "สุขอนามัย" },
    ],
    body: [
      "การเลือกใช้สุขภัณฑ์อัจฉริยะจากโคห์เลอร์ คือการยืนยันว่ารายละเอียดเป็นสิ่งสำคัญที่สุดสำหรับคุณ ด้วยนวัตกรรมเหนือชั้นผสานงานดีไซน์อย่างยากจะหาใครเทียบ สุขภัณฑ์อัจฉริยะจากโคห์เลอร์ทุกชิ้น กำเนิดจากความลุ่มหลงในรายละเอียดและงานฝีมืออันพิถีพิถัน เพื่อยกระดับประสบการณ์การใช้งานของคุณให้เหนือความคาดหมาย",
      "สุขภัณฑ์อัจฉริยะของโคห์เลอร์ทุกชิ้น รังสรรค์โดยคำนึงถึงความใส่ใจในการออกแบบ ความสะอาด สุขอนามัย และความเป็นส่วนตัวที่เหนือกว่า.",
      "เราเลือกใช้เทคโนโลยีโดยคำนึงถึงผู้ใช้งานเป็นศูนย์กลาง แล้วมองหาแรงบันดาลใจในการออกแบบจากธรรมชาติรอบตัว เพื่อรังสรรค์เป็นความงาม เข้าถึงง่าย และปรับแต่งได้เฉพาะตัว “สุขภัณฑ์อัจฉริยะของเรา เกิดจากทีมงานผู้เชี่ยวชาญทุกแขนง ไม่ว่าจะเป็นผู้เชี่ยวชาญด้านการใช้งาน ผู้เชี่ยวชาญด้านพฤติกรรมมนุษย์ และผู้เชี่ยวชาญด้านวิศวกรรมมารวมตัวกัน เพื่อหาจุดสมดุลในการออกแบบ จนได้ผลิตภัณฑ์ที่ตอบโจทย์ได้ดีที่สุด” Lun Cheak Tan รองประธานกรรมการด้านการออกแบบอุตสาหกรรมห้องครัวและห้องน้ำของโคห์เลอร์กล่าว",
      "ทุกการออกแบบ เราใส่ใจในเรื่องความสะอาดเป็นพิเศษ เพื่อให้คุณมั่นใจสูงสุด เช่นการฆ่าเชื้อด้วยแสงยูวีอันเป็นเอกสิทธิ์เฉพาะ การทำความสะอาดอัตโนมัติก่อนใช้งานเพื่อประสิทธิภาพการชำระล้างสูงสุด",
      "สุขภัณฑ์อัจฉริยะของโคห์เลอร์ มอบความสะอาดอย่างเหนือระดับให้กับผู้ใช้งาน ด้วยระบบชำระล้างและเปิด/ปิดฝาอัตโนมัติโดยไม่ต้องสัมผัสสุขภัณฑ์ ตลอดจนการฉีดชำระทั้งด้านหน้าและด้านหลังแบบสลับเป็นจังหวะ ก็ให้ความรู้สึกสบายและทำความสะอาดทุกจุดได้อย่างทั่วถึง",
      "พร้อมให้ผู้ใช้งานได้ปรับแต่งตามประสบการณ์ส่วนตัวของแต่ละคนด้วยรีโมทควบคุม ไม่ว่าจะเป็นความแรง อุณหภูมิ อุ่นที่นั่ง เป่าลมร้อน หรือแม้กระทั่งปรับแสงไฟ.",
      "หลอมรวมประสิทธิภาพ ความคุ้มค่า และความสะอาดเข้าด้วยกัน",
    ],
    videos: [
      { id: "QyIq3OJvXuA", title: "New Designer Toilets with Smart Features - KOHLER® Intelligent Toilets", poster: { src: "/lifestyle/editorial/yt-QyIq3OJvXuA-900.webp", srcSmall: "/lifestyle/editorial/yt-QyIq3OJvXuA-900.webp", width: 900, height: 506, alt: "New Designer Toilets with Smart Features - KOHLER® Intelligent Toilets" } },
    ],
    bannerVideo: "QyIq3OJvXuA",
  },
  {
    slug: "cleaner-toilets-revolution-360",
    title: { th: "สุขภัณฑ์จะช่วยเสริมสร้างสุขอนามัยให้ห้องน้ำของคุณได้อย่างไร", en: "สุขภัณฑ์จะช่วยเสริมสร้างสุขอนามัยให้ห้องน้ำของคุณได้อย่างไร" },
    excerpt: { th: "ห้องน้ำ... คือห้องที่ทุกคนในบ้านใช้งานบ่อยแต่ใช้เวลาในนั้นน้อยที่สุด ทุกครั้งที่เข้าออกก็มักจะมีฝุ่น เศษผงและสิ่งสกปรกต่าง ๆ ให้ต้องหมั่นทำความสะอาดอยู่เสมอ…", en: "ห้องน้ำ... คือห้องที่ทุกคนในบ้านใช้งานบ่อยแต่ใช้เวลาในนั้นน้อยที่สุด ทุกครั้งที่เข้าออกก็มักจะมีฝุ่น เศษผงและสิ่งสกปรกต่าง ๆ ให้ต้องหมั่นทำความสะอาดอยู่เสมอ…" },
    date: CAPTURED,
    tag: "เรื่องเล่าจาก KOHLER",
    tagEn: "From KOHLER",
    space: "bath",
    coverId: "aaa80571-1800x800",
    source: { url: "https://www.kohler.co.th/articles/cleaner-toilets-revolution-360.html", route: "/articles/cleaner-toilets-revolution-360.html" },
    hero: { src: "/lifestyle/editorial/cleaner-toilets-revolution-360-hero-1800.webp", srcSmall: "/lifestyle/editorial/cleaner-toilets-revolution-360-hero-900.webp", width: 1800, height: 1012, alt: "สุขภัณฑ์จะช่วยเสริมสร้างสุขอนามัยให้ห้องน้ำของคุณได้อย่างไร" },
    cover: { src: "/lifestyle/editorial/cleaner-toilets-revolution-360-fig1-1800.webp", srcSmall: "/lifestyle/editorial/cleaner-toilets-revolution-360-fig1-900.webp", width: 1800, height: 510, alt: "จะอยู่อย่างสะอาด หรืออยู่เพื่อทำแต่ความสะอาด ...คุณเลือกได้" },
    figures: [
      { src: "/lifestyle/editorial/cleaner-toilets-revolution-360-fig1-1800.webp", srcSmall: "/lifestyle/editorial/cleaner-toilets-revolution-360-fig1-900.webp", width: 1800, height: 510, alt: "จะอยู่อย่างสะอาด หรืออยู่เพื่อทำแต่ความสะอาด ...คุณเลือกได้" },
      { src: "/lifestyle/editorial/cleaner-toilets-revolution-360-fig2-1800.webp", srcSmall: "/lifestyle/editorial/cleaner-toilets-revolution-360-fig2-900.webp", width: 1800, height: 510, alt: "จะอยู่อย่างสะอาด หรืออยู่เพื่อทำแต่ความสะอาด ...คุณเลือกได้" },
      { src: "/lifestyle/editorial/cleaner-toilets-revolution-360-fig3-1800.webp", srcSmall: "/lifestyle/editorial/cleaner-toilets-revolution-360-fig3-900.webp", width: 1800, height: 510, alt: "จะอยู่อย่างสะอาด หรืออยู่เพื่อทำแต่ความสะอาด ...คุณเลือกได้" },
    ],
    body: [
      "ห้องน้ำ... คือห้องที่ทุกคนในบ้านใช้งานบ่อยแต่ใช้เวลาในนั้นน้อยที่สุด ทุกครั้งที่เข้าออกก็มักจะมีฝุ่น เศษผงและสิ่งสกปรกต่าง ๆ ให้ต้องหมั่นทำความสะอาดอยู่เสมอ ถ้าคุณกำลังมองหาผู้ช่วยเพื่อลดภาระการทำความสะอาดห้องน้ำอันน่าเบื่อของคุณเหมือนกับเรา เราขอแนะนำผู้ช่วยที่ดีที่สุด จากสิ่งที่คุณคาดไม่ถึงที่สุด ...นั่นก็คือโถสุขภัณฑ์",
      "ปี 2020 ทำให้เรารู้ว่า... มีหลายสิ่งหลายอย่างเปลี่ยนแปลงไป เราจำเป็นต้องปรับตัวหรือเปลี่ยนรูปแบบการใช้ชีวิต แนวคิดแบบมินิมอล เน้นความเรียบง่าย ดูจะตอบรับกับวิถีชีวิตแบบใหม่ได้ดีที่สุด ทั้งยังตอบโจทย์การออกแบบห้องน้ำ ไม่ใช่แค่ความสวยงาม แต่ต้องทำความสะอาดง่ายเพื่อสุขอนามัยที่ดีอีกด้วย ความสะอาดที่หลายคนกังวลและให้ความสำคัญที่สุด ส่งผลต่อการตัดสินใจเลือกซื้ออุปกรณ์และของตกแต่งในห้องน้ำมากขึ้น เช่นเลือกพื้นผิวเรียบลื่นเพราะจะง่ายต่อการทำความสะอาด เลือกตู้แขวนสำหรับจัดเก็บผลิตภัณฑ์เสริมความงาม หรือเครื่องสำอางที่ไม่ค่อยได้ใช้ เพื่อความเรียบร้อยสะอาดตา รวมถึงเลือกสุขภัณฑ์ที่ออกแบบอย่างสวยงามไร้กาลเวลา เพื่อเปลี่ยนโฉมห้องน้ำในบ้านให้เป็นพื้นที่สะอาดสดใสอยู่เสมอ",
      "ตู้แขวนและชั้นวางของที่จัดวางอย่างเป็นระเบียบ จะช่วยป้องกันฝุ่น แบคทีเรียและความชื้น ยิ่งต้องล้างมือบ่อย การยกระดับสุขอนามัยในห้องน้ำยิ่งเป็นเรื่องจำเป็น เช่นเปลี่ยนมาใช้ที่จ่ายสบู่เหลวแทนสบู่ก้อน เพราะถาดรองสบู่อาจเป็นแหล่งสะสมสิ่งสกปรก หรือเปลี่ยนมาใช้สุขภัณฑ์แบบ CleanCoat™",
      "จิตสำนึกด้านสุขอนามัยและความสะอาดที่เพิ่มสูงขึ้น เป็นแรงผลักดันให้เราอยากทำความสะอาดห้องน้ำให้บ่อยที่สุดและสะอาดที่สุด เราจึงเปิดหน้าต่างเพื่อระบายความชื้นอันเป็นแหล่งเพาะพันธุ์ของแบคทีเรีย เปิดพัดลมดูดอากาศขณะอาบน้ำ แขวนผ้าเช็ดตัวบนราวแขวนที่ออกแบบไว้ และคลี่ม่านอาบน้ำหลังการใช้เพื่อผึ่งให้แห้งสนิท แต่เมื่อเราไม่สามารถหลีกเลี่ยงการทำความสะอาดห้องน้ำได้ เราก็จะเลือกใช้ผลิตภัณฑ์ทำความสะอาดที่เป็นมิตรต่อสิ่งแวดล้อม หรือสูตรที่ทำเองในบ้านโดยไม่ใช้สารเคมี เพื่อให้เราสบายใจว่าได้มีส่วนในการดูแลและปกป้องโลก",
      "อีกหนึ่งทางเลือกคือการคิดค้นเทคโนโลยีของสุขภัณฑ์ เพื่อช่วยให้การทำความสะอาดมีประสิทธิภาพมากขึ้นกว่าเดิม ระบบ ContinuosClean",
      "ถ้าคุณกำลังมองหาสุขภัณฑ์ที่จะช่วยยกระดับการทำความสะอาดที่ดีกว่า คลิกที่นี่เพื่อรับข้อมูลเพิ่มเติม",
    ],
    videos: [
      { id: "D4BFqWmKwlE", title: "KOHLER CleanCoat", poster: { src: "/lifestyle/editorial/yt-D4BFqWmKwlE-640.webp", srcSmall: "/lifestyle/editorial/yt-D4BFqWmKwlE-640.webp", width: 640, height: 480, alt: "KOHLER CleanCoat" } },
    ],
    bannerVideo: null,
  },
  {
    slug: "choosing-the-perfect-kitchen-faucets",
    title: { th: "ข้อเสนอสำหรับครัวใหม่ในฝัน", en: "ข้อเสนอสำหรับครัวใหม่ในฝัน" },
    excerpt: { th: "ห้องครัวคือหัวใจสำคัญของบ้าน โดยที่ผู้ใช้งานหลักมีส่วนในการกำหนดพื้นที่ใช้สอย ตลอดหลายปีที่ผ่านมาเราได้ปรับเปลี่ยนพื้นที่ครัว…", en: "ห้องครัวคือหัวใจสำคัญของบ้าน โดยที่ผู้ใช้งานหลักมีส่วนในการกำหนดพื้นที่ใช้สอย ตลอดหลายปีที่ผ่านมาเราได้ปรับเปลี่ยนพื้นที่ครัว…" },
    date: CAPTURED,
    tag: "ไอเดียครัว",
    tagEn: "Kitchen ideas",
    space: "kitchen",
    coverId: "zab64028-1800x800",
    source: { url: "https://www.kohler.co.th/articles/choosing-the-perfect-kitchen-faucets.html", route: "/articles/choosing-the-perfect-kitchen-faucets.html" },
    hero: { src: "/lifestyle/editorial/choosing-the-perfect-kitchen-faucets-hero-1800.webp", srcSmall: "/lifestyle/editorial/choosing-the-perfect-kitchen-faucets-hero-900.webp", width: 1800, height: 1012, alt: "ข้อเสนอสำหรับครัวใหม่ในฝัน" },
    cover: { src: "/lifestyle/editorial/choosing-the-perfect-kitchen-faucets-fig1-1800.webp", srcSmall: "/lifestyle/editorial/choosing-the-perfect-kitchen-faucets-fig1-900.webp", width: 1800, height: 510, alt: "ข้อเสนอสำหรับครัวใหม่ในฝัน" },
    figures: [
      { src: "/lifestyle/editorial/choosing-the-perfect-kitchen-faucets-fig1-1800.webp", srcSmall: "/lifestyle/editorial/choosing-the-perfect-kitchen-faucets-fig1-900.webp", width: 1800, height: 510, alt: "ข้อเสนอสำหรับครัวใหม่ในฝัน" },
      { src: "/lifestyle/editorial/choosing-the-perfect-kitchen-faucets-fig2-1800.webp", srcSmall: "/lifestyle/editorial/choosing-the-perfect-kitchen-faucets-fig2-900.webp", width: 1800, height: 255, alt: "ออกแบบใหม่ให้กับพื้นที่โปรดปรานของคุณ" },
      { src: "/lifestyle/editorial/choosing-the-perfect-kitchen-faucets-fig3-1800.webp", srcSmall: "/lifestyle/editorial/choosing-the-perfect-kitchen-faucets-fig3-900.webp", width: 1800, height: 510, alt: "องค์ประกอบสำคัญที่สุดของการออกแบบ" },
    ],
    body: [
      "ห้องครัวคือหัวใจสำคัญของบ้าน โดยที่ผู้ใช้งานหลักมีส่วนในการกำหนดพื้นที่ใช้สอย ตลอดหลายปีที่ผ่านมาเราได้ปรับเปลี่ยนพื้นที่ครัว ให้รับใช้ทั้งผู้ที่รักการทำอาหารแบบง่าย ๆ ไปจนถึงเชฟฝีมือดี เพราะห้องครัวเป็นได้มากกว่าที่จัดเตรียมหรือรับประทานอาหาร แต่ยังเป็นทั้งพื้นที่อเนกประสงค์ พื้นที่ทำงาน ห้องเรียนโฮมสคูล พื้นที่เก็บของ หรือแม้แต่เป็นศูนย์รวมของความบันเทิง",
      "ห้องครัวมักใช้เป็นพื้นที่อเนกประสงค์ สำหรับครอบครัวและเพื่อนฝูงที่จะช่วยเติมเต็มความสุขทั้งทางกาย ทางใจและจิตวิญญาณร่วมกัน ใช้งานได้จริงและสะท้อนบุคลิกของเจ้าของบ้าน ปัจจุบันเราใช้เวลาช้อปปิ้งในซูเปอร์มาร์เก็ตน้อยลง แต่เราใช้เวลาทำอาหารและร่วมรับประทานอยู่ที่บ้านมากขึ้น เราจึงต้องการห้องครัวที่ตอบโจทย์ด้านความสะอาดมากขึ้นด้วยเช่นกัน",
      "ห้องครัวที่มีแปลนแบบเปิดโล่ง สามารถพัฒนาไปเป็นพื้นที่ทานอาหาร ทำงาน และพักผ่อน การออกแบบใหม่ให้กับห้องครัวจึงควรพิจารณาในจุดนี้ เพื่อให้ห้องโปรดของคุณมีความสะดวกสบาย ปลอดภัย และให้ความสุขได้แท้จริง การใช้สอยของห้องครัวไม่ได้ถูกจำกัดด้วยขนาดของพื้นที่ แต่อยู่ที่การจัดวางอย่างมีประสิทธิภาพและสวยงามดูดี หากอยากปรับเปลี่ยนเพียงเล็กน้อย คุณอาจใช้ฉากกั้น เฟอร์นิเจอร์ลอยตัว หรือต้นไม้ มาช่วยในการแบ่งสัดส่วนของพื้นที่ได้ แต่สิ่งที่จะช่วยเปลี่ยนโฉมห้องครัวได้ง่ายและรวดเร็วที่สุดก็คือ การเปลี่ยนก๊อกน้ำและอ่างล้างจาน",
      "การลงทุนซื้ออุปกรณ์ติดตั้งในห้องครัวเหล่านี้นับว่าเป็นเรื่องคุ้มค่า เช่นก๊อกน้ำซึ่งถูกใช้งานบ่อยครั้งที่สุด การเลือกก๊อกน้ำดีไซน์หรูให้เข้าคู่กัน สามารถสร้างการเปลี่ยนแปลงให้กับห้องครัวของคุณอย่างคาดไม่ถึง ช่วยให้คุณทำงานครัวได้อย่างเต็มประสิทธิภาพ ไม่ว่าจะเป็นการจัดเตรียม การทำอาหาร ตลอดจนการทำความสะอาด ก๊อกน้ำดีไซน์สวยเป็นเสมือนงานประติมากรรมที่ช่วยกำหนดทิศทางการตกแต่ง และการเลือกผิวสัมผัสที่เหมาะสม ก็จะช่วยสร้างความกลมกลืนกับองค์ประกอบอื่นให้ห้องครัวสวยงามและโดดเด่นมากขึ้น",
      "นวัตกรรมสำหรับห้องครัวก็เป็นเรื่องสำคัญ ก๊อกน้ำรุ่น Malleco kitchen faucet",
      "มุมมองของระบบนิเวศที่สะอาด อาจสร้างแรงบันดาลใจให้คุณขยับขยายการออกแบบ จากห้องครัวสู่พื้นที่อื่น ๆ อย่างเช่น การเปลี่ยนตู้แขวนสำหรับเก็บของในครัว หรือเลือกกระเบื้องตกแต่งที่ยับยั้งการก่อตัวของแบคทีเรีย ปราศจากรูพรุน และไม่ก่อให้เกิดคราบไคล เพื่อห้องครัวที่สะอาดอยู่เสมอ ให้คุณได้เพลิดเพลินกับห้องครัวที่สวยงาม ใช้งานได้อเนกประสงค์กับคนที่คุณรัก และบ่งบอกถึงไลฟ์สไตล์ความเป็นคุณ",
    ],
    videos: [
      { id: "cEiG69F-pMo", title: "Kohler Malleco Touchless Kitchen Faucet", poster: { src: "/lifestyle/editorial/yt-cEiG69F-pMo-640.webp", srcSmall: "/lifestyle/editorial/yt-cEiG69F-pMo-640.webp", width: 640, height: 480, alt: "Kohler Malleco Touchless Kitchen Faucet" } },
    ],
    bannerVideo: null,
  },
  {
    slug: "functional-beauty-reconsidering-the-kitchen-sink",
    title: { th: "ความงามที่มาพร้อมกับฟังก์ชั่นการใช้งานกับอ่างล้างจานในมุมมองใหม่", en: "ความงามที่มาพร้อมกับฟังก์ชั่นการใช้งานกับอ่างล้างจานในมุมมองใหม่" },
    excerpt: { th: "ทุกวันนี้ห้องครัวมีอเนกประสงค์หลายอย่างมากกว่าที่เคยเป็น ซึ่งแตกต่างจากไม่กี่ปีที่ผ่านมาอย่างมาก…", en: "ทุกวันนี้ห้องครัวมีอเนกประสงค์หลายอย่างมากกว่าที่เคยเป็น ซึ่งแตกต่างจากไม่กี่ปีที่ผ่านมาอย่างมาก…" },
    date: CAPTURED,
    tag: "ไอเดียครัว",
    tagEn: "Kitchen ideas",
    space: "kitchen",
    coverId: "zab86829-1800x800",
    source: { url: "https://www.kohler.co.th/articles/functional-beauty-reconsidering-the-kitchen-sink-artilcle.html", route: "/articles/functional-beauty-reconsidering-the-kitchen-sink-artilcle.html" },
    hero: { src: "/lifestyle/editorial/functional-beauty-reconsidering-the-kitchen-sink-hero-1800.webp", srcSmall: "/lifestyle/editorial/functional-beauty-reconsidering-the-kitchen-sink-hero-900.webp", width: 1800, height: 800, alt: "ความงามที่มาพร้อมกับฟังก์ชั่นการใช้งานกับอ่างล้างจานในมุมมองใหม่" },
    cover: { src: "/lifestyle/editorial/functional-beauty-reconsidering-the-kitchen-sink-fig1-1800.webp", srcSmall: "/lifestyle/editorial/functional-beauty-reconsidering-the-kitchen-sink-fig1-900.webp", width: 1800, height: 1350, alt: "พื้นที่ใช้สอยขนาดใหญ่" },
    figures: [
      { src: "/lifestyle/editorial/functional-beauty-reconsidering-the-kitchen-sink-fig1-1800.webp", srcSmall: "/lifestyle/editorial/functional-beauty-reconsidering-the-kitchen-sink-fig1-900.webp", width: 1800, height: 1350, alt: "พื้นที่ใช้สอยขนาดใหญ่" },
      { src: "/lifestyle/editorial/functional-beauty-reconsidering-the-kitchen-sink-fig2-1800.webp", srcSmall: "/lifestyle/editorial/functional-beauty-reconsidering-the-kitchen-sink-fig2-900.webp", width: 1800, height: 1200, alt: "ตำแหน่ง หรือ จุดติดตั้ง" },
      { src: "/lifestyle/editorial/functional-beauty-reconsidering-the-kitchen-sink-fig3-1800.webp", srcSmall: "/lifestyle/editorial/functional-beauty-reconsidering-the-kitchen-sink-fig3-900.webp", width: 1800, height: 1350, alt: "หวนรำลึกถึงอดีต" },
    ],
    body: [
      "ทุกวันนี้ห้องครัวมีอเนกประสงค์หลายอย่างมากกว่าที่เคยเป็น ซึ่งแตกต่างจากไม่กี่ปีที่ผ่านมาอย่างมาก เพื่อให้มองเห็นภาพว่าห้องครัวสมัยใหม่มีประสิทธิภาพเพียงใดคุณอาจลองมองสิ่งที่อยู่ใกล้ตัว เช่น อ่างล้างจานที่ครั้งหนึ่งเคยเรียบง่าย นักออกแบบอัจฉริยะกำลังสร้างอ่างล้างจานที่มีประโยชน์มากกว่าแค่เก็บน้ำ.",
      "ขณะที่อ่างล้างจานในครัวแบบเก่าอาจมีความลึกเพียงแค่ 6-7 นิ้ว แต่ทุกวันนี้อ่างล้างจานมักจะมีความลึกประมาณ 9-10 นิ้ว เพื่อรองรับหม้อและกระทะขนาดใหญ่ ความลึกที่เพิ่มขึ้นยังช่วยจำกัดระยะการกระเซ็นของน้ำได้อีกด้วย.",
      "อ่างล้างรุ่นใหม่จะทำให้การทำงานในห้องครัวมีความสุขมากขึ้นและน่าเบื่อน้อยลง.",
      "อ่างล้างจานสำหรับเตรียมวัตถุดิบหรือเรียกอีกอย่างว่า อ่างล้างจานแบบฝังบนเคาน์เตอร์ จะช่วยลดความแออัดรอบอ่างที่ใช้งานหลัก อ่าง Eolia® เหมาะสำหรับการล้างอย่างรวดเร็วหรือเก็บน้ำแข็งหรือละลายน้ำแข็ง.",
      "อ่างล้างจานชนิดรางขนาดยาวและบางเหมาะอย่างยิ่งสำหรับห้องครัวที่ต้องการทำให้มีพื้นที่วางอ่างแคบที่สุด และช่วยให้ทำงานพร้อมกันได้โดยไม่ชนกัน อ่างเตรียมวัตถุดิบ Crevasse® ที่มีรูปร่างเรียวบางมาพร้อมกับระบบการกำจัดขยะแบบทำงานร่วมกันด้วยเทคโนโลยีชั้นสูงซึ่งช่วยให้การทำความสะอาดเป็นไปอย่างรวดเร็ว.",
      "อ่างล้างมือหรืออ่างสไตล์บ้านไร่ที่เป็นอมตะอยู่เหนือกาลเวลากำลังกลับมาอยู่ในบ้านอีกครั้งด้วยสีพื้นผิวและวัสดุที่หลากหลายขึ้นกว่าที่เคยเนื่องด้วยนวัตกรรมที่ใส่ลงไปในรูปแบบคลาสสิกนี้ส่งผลให้เป็นมากกว่าแค่สไตล์คลาสสิก อ่างล้างมือรุ่น Whitehaven™ และ Vault™ โดดเด่นด้วยดีไซน์ Self-Trimming® แบบปฏิวัติเพื่อให้สามารถติดตั้งได้ง่ายในตู้วางอ่างที่มีอยู่แล้ว.",
      "มีวัสดุประเภทต่างๆ ให้เลือกใช้งานมากมาย อาทิเช่น อ่างล้างประเภทไฟร์เคลย์มักเป็นตัวเลือกที่นิยมเสมอเนื่องจากความทนทานและความงาม เหล็กหล่อเคลือบอีนาเมลเป็นวัสดุคลาสสิกที่ไม่เพียงแต่แข็งแรงเท่านั้น แต่ยังมีสีสันหลากหลายให้เลือกใช้งานซึ่งเป็นอีกหนึ่งทางเลือกในการสร้างสรรค์รูปลักษณ์ของห้องครัวให้มีเอกลักษณ์อย่างแท้จริง สแตนเลส สตีล ที่มีภาพลักษณ์ภายนอกซับซ้อนเหนือกาลเวลาและเข้ากันได้ดีกับพื้นผิวของเครื่องใช้ในห้องครัวที่ทันสมัย.",
      "อ่างล้างจานรุ่นใหม่บางรุ่นมาพร้อมกับการออกแบบที่มีลักษณะเป็นชั้นเก็บของและมีนวัตกรรมซึ่งช่วยให้มีพื้นที่จัดเก็บเพิ่มเติม พื้นผิวสำหรับการทำงานที่กว้างขวางขึ้น มีถาดเก็บของแบบซ้อนเป็นชั้น เขียงแบบเลื่อน และอุปกรณ์เสริมที่ช่วยให้อ่างมีทั้งความอเนกประสงค์และความเป็นระเบียบอย่างสูงสุด.",
      "อุปกรณ์เสริมสำหรับอ่างในปัจจุบันมีความหลากหลายมากขึ้น ซึ่งมากกว่าที่มีอยู่ในเครื่องจ่ายสบู่เหลวแบบบิวท์อินอีกด้วย เช่น กระชอนที่มีขนาดเหมาะเจาะกับอ่างของคุณโดยเฉพาะ เขียงและแผ่นระบายน้ำ ชั้นวางอุปกรณ์พร้อม \"ถ้วยแช่\" ตะกร้าลวดสำหรับล้างผักผลไม้ และชั้นวางผึ่งสิ่งของให้แห้ง สำหรับตัวอย่างที่ยอดเยี่ยม ได้แก่ อ่าง KOHLER Prolific™ เป็นอ่างที่พิสูจน์ให้เห็นว่าอ่างของคุณคือพื้นที่ทำงานที่เป็นประโยชน์อย่างแท้จริงสำหรับห้องครัว.",
    ],
    videos: [],
    bannerVideo: null,
  },
  {
    slug: "designing-the-perfect-powder-room",
    title: { th: "การออกแบบห้องแต่งตัวให้สมบูรณ์แบบ", en: "การออกแบบห้องแต่งตัวให้สมบูรณ์แบบ" },
    excerpt: { th: "บ่อยครั้งที่ห้องแต่งตัวเป็นหนึ่งในห้องที่ใช้เงินลงทุนสำหรับการปรับปรุงซ่อมแซมน้อยที่สุดในบ้าน…", en: "บ่อยครั้งที่ห้องแต่งตัวเป็นหนึ่งในห้องที่ใช้เงินลงทุนสำหรับการปรับปรุงซ่อมแซมน้อยที่สุดในบ้าน…" },
    date: CAPTURED,
    tag: "ไอเดียห้องน้ำ",
    tagEn: "Bathroom ideas",
    space: "bath",
    coverId: "bancroft-02",
    source: { url: "https://www.kohler.co.th/articles/designing-the-perfect-powder-room-article.html", route: "/articles/designing-the-perfect-powder-room-article.html" },
    hero: { src: "/lifestyle/editorial/designing-the-perfect-powder-room-hero-900.webp", srcSmall: "/lifestyle/editorial/designing-the-perfect-powder-room-hero-900.webp", width: 900, height: 1350, alt: "การออกแบบห้องแต่งตัวให้สมบูรณ์แบบ" },
    cover: { src: "/lifestyle/editorial/designing-the-perfect-powder-room-fig1-1800.webp", srcSmall: "/lifestyle/editorial/designing-the-perfect-powder-room-fig1-900.webp", width: 1800, height: 1350, alt: "เปลี่ยนแปลงเล็กน้อย" },
    figures: [
      { src: "/lifestyle/editorial/designing-the-perfect-powder-room-fig1-1800.webp", srcSmall: "/lifestyle/editorial/designing-the-perfect-powder-room-fig1-900.webp", width: 1800, height: 1350, alt: "เปลี่ยนแปลงเล็กน้อย" },
      { src: "/lifestyle/editorial/designing-the-perfect-powder-room-fig2-1800.webp", srcSmall: "/lifestyle/editorial/designing-the-perfect-powder-room-fig2-900.webp", width: 1800, height: 1350, alt: "เพิ่มพื้นที่ให้ห้องดูกว้างขึ้น" },
    ],
    body: [
      "บ่อยครั้งที่ห้องแต่งตัวเป็นหนึ่งในห้องที่ใช้เงินลงทุนสำหรับการปรับปรุงซ่อมแซมน้อยที่สุดในบ้าน คุณสามารถสร้างการเปลี่ยนแปลงครั้งยิ่งใหญ่นี้ได้เพียงแค่เพิ่มอุปกรณ์เล็กๆ น้อยๆ เช่น อ่างล้างหน้าหรือก๊อกน้ำอันใหม่ หรือเปลี่ยนพื้นผิวด้านบนของเคาน์เตอร์ใหม่ ลองทำตามเคล็ดลับต่อไปนี้เพื่อเพิ่มความสดชื่นให้กับพื้นที่ซึ่งเปรียบเสมือนอัญมณีแห่งนี้",
      "พื้นไม้เนื้อแข็งกำลังเป็นที่นิยมในขณะนี้ เช่นเดียวกับวัสดุที่ให้ความรู้สึกหรูหราอย่างหินแกรนิตและหินอ่อน ซึ่งช่วยทำให้ห้องดูหรูหราขึ้น ปูพื้นด้วยวัสดุชนิดเดียวกันจากโถงทางเดินเข้ามาในห้องแต่งตัวเพื่อมอบความรู้สึกเป็นธรรมชาติ",
      "เปลี่ยนก๊อกน้ำของคุณจากสไตล์ดั้งเดิมเป็นก๊อกน้ำสไตล์ทันสมัยเพรียวบาง ซึ่งสามารถสร้างความแตกต่างได้อย่างชัดเจน อย่างไรก็ตามคุณควรพิจารณาวัสดุตกแต่งปิดผิวด้วยเพื่อให้ก๊อกน้ำเข้ากันได้กับดีไซน์โดยรวม",
      "สีของผนังหรือเพดานที่ให้ความรู้สึกแข็งแรงช่วยสร้างผลลัพธ์ที่เด่นชัดให้กับห้องและเพิ่มองค์ประกอบที่น่าสนใจได้ตลอดโถงทางเดิน",
      "สำหรับเคาน์เตอร์ห้องแต่งตัว ลองเลือกวัสดุสีสันสดใสหรือสะท้อนเงา เช่น หินแกรนิต หรือแก้วควอตซ์ หินชนวนซึ่งให้ความอบอุ่นมากกว่ากระเบื้องเซรามิกสามารถนำมาควบรวมกับหินแกรนิตหรือแก้วควอตซ์เพื่อสร้างความรู้สึกสุขุม ไม่ทำให้รูปลักษณ์การตกแต่งดูมากจนเกินไป คุณอาจพิจารณากระจกรีไซเคิล หากคุณกำลังมองหาทางเลือกในการอนุรักษ์ธรรมชาติแต่ยังต้องการความทนทานและเปล่งประกาย",
      "เพิ่มพื้นที่ใช้งานภายในห้องของคุณด้วยการใช้อ่างล้างหน้าแบบแขวนพร้อมขารองอ่างแบบตั้งพื้นสำหรับพื้นที่พิเศษและการจัดเก็บสิ่งของ ลองพิจารณา ตู้วางอ่างขนาดเล็ก",
      "แสงไฟสามารถช่วยเพิ่มความรู้สึกโดยรวมหรือสร้างธีมให้กับห้องแต่งตัวของคุณได้ การให้แสงสว่างที่มากไว้ก่อนย่อมดีกว่าการให้แสงที่ไม่เพียงพอ นอกจากนี้คุณยังสามารถใช้สวิตช์เพื่อหรี่แสงไฟได้อีกด้วย",
      "คงความเรียบง่าย ไม่ตกแต่งมากเกินไป ควรให้เคาน์เตอร์มีพื้นที่ว่างเพื่อให้แขกสามารถวางกระเป๋าหรือกุญแจรถได้ และให้ความสำคัญกับการเลือกของประดับตกแต่ง เช่น ราวแขวนผ้าเช็ดตัว ห่วงสำหรับคล้องผ้าเช็ดตัว และเครื่องจ่ายสบู่ นอกจากนี้คุณควรพิจารณาเป็นพิเศษสำหรับพื้นที่วางกระเป๋าถือของสุภาพสตรี เช่น เคาน์เตอร์หรือชั้นวางของที่มีพื้นที่ว่าง เป็นต้น",
      "« Lihat Kiat-kiat Lain untuk Kamar Mandi",
    ],
    videos: [],
    bannerVideo: null,
  },
  {
    slug: "remix-your-routine",
    title: { th: "สร้างสรรค์บทเพลงความสุขให้ทุกวัน ด้วยชุดฝักบัวผสานเสียงเพลง Moxie", en: "สร้างสรรค์บทเพลงความสุขให้ทุกวัน ด้วยชุดฝักบัวผสานเสียงเพลง Moxie" },
    excerpt: { th: "ชุดฝักบัว Moxie ให้คุณอาบสนุก ปลุกพลังด้วยเพลงที่คุณโปรดปราน", en: "ชุดฝักบัว Moxie ให้คุณอาบสนุก ปลุกพลังด้วยเพลงที่คุณโปรดปราน" },
    date: CAPTURED,
    tag: "เรื่องเล่าจาก KOHLER",
    tagEn: "From KOHLER",
    space: "bath",
    coverId: "aaa68050-43",
    source: { url: "https://www.kohler.co.th/articles/remix-your-routine.html", route: "/articles/remix-your-routine.html" },
    hero: { src: "/lifestyle/editorial/remix-your-routine-hero-1800.webp", srcSmall: "/lifestyle/editorial/remix-your-routine-hero-900.webp", width: 1800, height: 1012, alt: "สร้างสรรค์บทเพลงความสุขให้ทุกวัน ด้วยชุดฝักบัวผสานเสียงเพลง Moxie" },
    cover: { src: "/lifestyle/editorial/remix-your-routine-fig1-1800.webp", srcSmall: "/lifestyle/editorial/remix-your-routine-fig1-900.webp", width: 1800, height: 510, alt: "อาบ...เพื่อคุณภาพชีวิต" },
    figures: [
      { src: "/lifestyle/editorial/remix-your-routine-fig1-1800.webp", srcSmall: "/lifestyle/editorial/remix-your-routine-fig1-900.webp", width: 1800, height: 510, alt: "อาบ...เพื่อคุณภาพชีวิต" },
      { src: "/lifestyle/editorial/remix-your-routine-fig2-1800.webp", srcSmall: "/lifestyle/editorial/remix-your-routine-fig2-900.webp", width: 1800, height: 510, alt: "ให้สายน้ำและเสียงเพลงปลุกเร้าพลังงานชีวิต" },
      { src: "/lifestyle/editorial/remix-your-routine-fig3-1800.webp", srcSmall: "/lifestyle/editorial/remix-your-routine-fig3-900.webp", width: 1800, height: 532, alt: "เติมพลังบวกด้วยพลังเสียง" },
    ],
    body: [
      "ชุดฝักบัว Moxie ให้คุณอาบสนุก ปลุกพลังด้วยเพลงที่คุณโปรดปราน",
      "ให้การอาบน้ำอันเป็นกิจวัตรประจำวันของคุณกลายเป็นช่วงเวลาสุดพิเศษ ด้วยสายน้ำซึ่งจะ ปลดปล่อยคุณจากความกังวลทั้งปวง สัมผัสความสุขได้มากขึ้น เพิ่มพลังบวกให้ชีวิตได้มากกว่า ไม่ว่าจะอยู่ในวัยไหน ผ่านความเหนื่อยล้ามาเท่าไหร่ การปรนนิบัติและบำเรอความสุขในยามอาบน้ำ คือรางวัลชีวิตที่จะทำให้เรารู้สึกดีขึ้น",
      "หลายคนมีความสุขกับการฟังเพลงขณะอาบน้ำ ซึ่งตรงตามศาสตร์แห่งการบำบัดด้วยเสียง เพราะเสียงเพลงจะไหลเวียนทั่วร่างกายและกระตุ้นสมองให้ตื่นตัว เสียงคือกุญแจสำคัญในการช่วยลดความตึงเครียดและบรรเทาความอ่อนล้า ไม่ว่าจะเป็นเสียงบรรยากาศของธรรมชาติ ความคึกคักของดนตรีแนวเทคโน ซิมโฟนีเพลงคลาสสิก หรือแนวเพลงอื่น ๆ ที่คุณโปรดปราน หากเป็นคุณภาพเสียงซึ่งมาจากลำโพงชั้นดีจะยิ่งช่วยให้คุณให้คุณผ่อนคลายและดีต่อสุขภาพมากขึ้น ชุดฝักบัว Moxie จึงมาพร้อมกับลำโพงไร้สายเข้าชุดกัน เพื่อคุณภาพเสียงที่ชัดใส สร้างความเพลิดเพลินในห้องน้ำที่เป็นดั่งที่หลบภัยของคุณ",
      "ไปให้สุดกับประสบการณ์การอาบน้ำที่เหนือกว่าด้วยเสียงเพลงที่คุณร้องเอง เพราะการร้องเพลงขณะอาบน้ำคือการบำบัดและการทำสมาธิชั้นเยี่ยม พื้นที่ขนาดเล็กของห้องน้ำจะช่วยให้เสียงของคุณก้องกังวานและเพิ่มความทุ้มให้เนื้อเสียง ยิ่งมีพลังยิ่งเพิ่มความมั่นใจ ทั้งยังช่วยบริหารกล้ามเนื้อใบหน้าให้กระชับและลดเลือนริ้วรอยได้เป็นอย่างดี",
      "หลังอาบน้ำพร้อมให้คุณพกพาความสุขสำหรับผ่อนคลายไปได้ตลอดวัน เพราะลำโพงไร้สายHarman Kardon ของชุดฝักบัว Moxie สามารถถอดออกเพื่อนำไปใช้ฟังเพลงต่อในห้องนอนหรือพกพาไปนอกบ้านได้ทุกที่ จะเลือกสนุกกับเสียงเพลงหรือสลับเป็นโหมดโทรศัพท์เพื่อรับสายจากครอบครัวหรือเพื่อนร่วมงานก็แสนสะดวก",
      "แค่โยกย้ายไปตามจังหวะเพลงขณะอาบน้ำก็อาจทำให้หลายคนแจ้งเกิดเป็นดาวเด่นได้ในชั่วข้ามคืน อย่าลืมนำลำโพงไร้สายนี้ติดตัวไปด้วยทุกที่เพื่อแชร์ความสุขจากเสียงเพลงให้เพื่อนฝูงและคนในครอบครัว ดีไซน์และเทคโนโลยีสุดล้ำที่ชวนฟังและชวนมองนี้ ชาร์จเพียงครั้งเดียวก็อยู่ได้นานถึง 9 ชั่วโมง สนใจข้อมูลเพิ่มเติม ติดตามได้ที่ Moxie handshower and wireless speaker",
    ],
    videos: [],
    bannerVideo: null,
  },
  {
    slug: "cooking-like-a-pro",
    title: { th: "ปรุงอาหารอย่างมืออาชีพ", en: "ปรุงอาหารอย่างมืออาชีพ" },
    excerpt: { th: "การทำอาหารกลับมาเป็นที่นิยมอีกครั้ง โดยเน้นไปที่อาหารที่ดีต่อสุขภาพและความสนุกสนานกับครอบครัวและเพื่อนฝูง…", en: "การทำอาหารกลับมาเป็นที่นิยมอีกครั้ง โดยเน้นไปที่อาหารที่ดีต่อสุขภาพและความสนุกสนานกับครอบครัวและเพื่อนฝูง…" },
    date: CAPTURED,
    tag: "ไอเดียครัว",
    tagEn: "Kitchen ideas",
    space: "kitchen",
    coverId: "zaa98109",
    source: { url: "https://www.kohler.co.th/articles/cooking-like-a-pro.html", route: "/articles/cooking-like-a-pro.html" },
    hero: { src: "/lifestyle/editorial/cooking-like-a-pro-hero-1800.webp", srcSmall: "/lifestyle/editorial/cooking-like-a-pro-hero-900.webp", width: 1800, height: 1350, alt: "ปรุงอาหารอย่างมืออาชีพ" },
    cover: { src: "/lifestyle/editorial/cooking-like-a-pro-fig1-1800.webp", srcSmall: "/lifestyle/editorial/cooking-like-a-pro-fig1-900.webp", width: 1800, height: 1350, alt: "สร้างเพื่อความถาวร" },
    figures: [
      { src: "/lifestyle/editorial/cooking-like-a-pro-fig1-1800.webp", srcSmall: "/lifestyle/editorial/cooking-like-a-pro-fig1-900.webp", width: 1800, height: 1350, alt: "สร้างเพื่อความถาวร" },
      { src: "/lifestyle/editorial/cooking-like-a-pro-fig2-1800.webp", srcSmall: "/lifestyle/editorial/cooking-like-a-pro-fig2-900.webp", width: 1800, height: 1081, alt: "อ่างล้างจาน" },
      { src: "/lifestyle/editorial/cooking-like-a-pro-fig3-1800.webp", srcSmall: "/lifestyle/editorial/cooking-like-a-pro-fig3-900.webp", width: 1800, height: 1350, alt: "ทำให้ทุกอย่างง่ายขึ้น" },
    ],
    body: [
      "การทำอาหารกลับมาเป็นที่นิยมอีกครั้ง โดยเน้นไปที่อาหารที่ดีต่อสุขภาพและความสนุกสนานกับครอบครัวและเพื่อนฝูง ซึ่งแรงบันดาลใจส่วนหนึ่งมาจากรายการทำอาหารทางทีวีที่เกิดขึ้นจำนวนมาก จึงทำให้ทุกอย่างดูง่ายขึ้น",
      "ผู้คนใช้เวลาอยู่ในห้องครัวและสนุกสนานกับการปรุงอาหารมากขึ้น ดังนั้น พวกเขาจึงต้องการห้องครัวที่มีประสิทธิภาพเทียบเท่าระดับมืออาชีพ.",
      "สแตนเลส สตีล สำหรับอ่างล้างจาน ตู้เย็น และเตาแก๊สเป็นตัวเลือกแรกสำหรับมืออาชีพทั้งหลาย เพราะช่วยต่อต้านริ้วรอยและรอยขีดข่วน อีกทั้งยังง่ายต่อการบำรุงรักษา ผู้บริโภคส่วนใหญ่ยังคงชอบรูปลักษณ์ที่ดูสะอาดตาของสแตนเลส สตีล แม้ว่าพวกเขาจะระมัดระวังไม่ให้การแต่งห้องครัวออกมาเป็นสไตล์ไฮเทคแบบสุดขั้วก็ตาม.",
      "หัวหน้าพ่อครัวในห้องอาหารชั้นนำและเชฟประจำบ้านมีสิ่งที่เหมือนกันคือ มักจะมีงานอย่างน้อยสามอย่างพร้อมๆกันในขณะที่พวกเขาเตรียมอาหารที่ซับซ้อน อ่างล้างจานก้นลึกอย่างน้อยสองหลุมสามารถลดขั้นตอนสับเปลี่ยนหม้อและกระทะ และทำให้ขั้นตอนง่ายขึ้น ประหยัดเวลาและพลังงาน.",
      "ค้นหาอ่างล้างจานที่มีอุปกรณ์มากมายเพื่อเสริมสไตล์การทำอาหารของคุณ เขียงแบบเคลื่อนย้ายได้ ตะกร้าล้างผักผลไม้และถาดต่างๆ รวมถึงที่วางของที่จะทำให้การเตรียมวัตถุดิบเป็นเรื่องง่ายและสนุกสนานมากขึ้น อ่างล้างจาน Kohler Moraine™ มีอุปกรณ์เสริมที่เหมาะสำหรับแต่ละขั้นตอนในการทำอาหาร.",
      "หลังจากรับประทานอาหารมื้อใหญ่ คุณต้องการให้การล้างทำความสะอาดเป็นไปอย่างรวดเร็วเพื่อที่จะสามารถออกจากห้องครัวและกลับไปพูดคุยกับแขกของคุณ ก๊อกน้ำแบบโค้งสูงและก๊อกน้ำแบบฉีดพ่นช่วยให้คุณได้ใกล้ชิดกับงานของคุณโดยการกำหนดเป้าหมายและฉีดพ่นตรงที่คุณต้องการอย่างแม่นยำ อ่างล้าง Smart Divide® ลดระดับแผ่นกั้นระหว่างอ่างล้างลงมา ทำให้ง่ายต่อการทำความสะอาดอุปกรณ์ทำครัวและจานชามจำนวนมาก และก๊อกน้ำที่มี Sweep Spray™ มีหัวฉีดทำมุมแบบพิเศษซึ่งเป็นใบมีดตัดน้ำที่กว้างและมีพลังเพื่อกวาดจานและอ่างล้างของคุณให้สะอาด.",
    ],
    videos: [],
    bannerVideo: null,
  },
  {
    slug: "easy-affordable-bath-upgrades",
    title: { th: "ปรับปรุงห้องน้ำของคุณอย่างง่ายดายและคุ้มค่า", en: "ปรับปรุงห้องน้ำของคุณอย่างง่ายดายและคุ้มค่า" },
    excerpt: { th: "ถ้าห้องน้ำของคุณใช้งานมาจนดูเก่าแต่คุณยังไม่พร้อมในเรื่องค่าใช้จ่ายของการปรับปรุงห้องน้ำใหม่อย่างเต็มรูปแบบ…", en: "ถ้าห้องน้ำของคุณใช้งานมาจนดูเก่าแต่คุณยังไม่พร้อมในเรื่องค่าใช้จ่ายของการปรับปรุงห้องน้ำใหม่อย่างเต็มรูปแบบ…" },
    date: CAPTURED,
    tag: "ไอเดียห้องน้ำ",
    tagEn: "Bathroom ideas",
    space: "bath",
    coverId: "aaa68094-rgb",
    source: { url: "https://www.kohler.co.th/articles/easy-affordable-bath-upgrades.html", route: "/articles/easy-affordable-bath-upgrades.html" },
    hero: { src: "/lifestyle/editorial/easy-affordable-bath-upgrades-hero-1800.webp", srcSmall: "/lifestyle/editorial/easy-affordable-bath-upgrades-hero-900.webp", width: 1800, height: 1238, alt: "ปรับปรุงห้องน้ำของคุณอย่างง่ายดายและคุ้มค่า" },
    cover: { src: "/lifestyle/editorial/easy-affordable-bath-upgrades-fig1-1800.webp", srcSmall: "/lifestyle/editorial/easy-affordable-bath-upgrades-fig1-900.webp", width: 1800, height: 1194, alt: "เปลี่ยนหัวฝักบัวอาบน้ำของคุณ" },
    figures: [
      { src: "/lifestyle/editorial/easy-affordable-bath-upgrades-fig1-1800.webp", srcSmall: "/lifestyle/editorial/easy-affordable-bath-upgrades-fig1-900.webp", width: 1800, height: 1194, alt: "เปลี่ยนหัวฝักบัวอาบน้ำของคุณ" },
      { src: "/lifestyle/editorial/easy-affordable-bath-upgrades-fig2-1800.webp", srcSmall: "/lifestyle/editorial/easy-affordable-bath-upgrades-fig2-900.webp", width: 1800, height: 1200, alt: "ประตูกระจก" },
      { src: "/lifestyle/editorial/easy-affordable-bath-upgrades-fig3-1800.webp", srcSmall: "/lifestyle/editorial/easy-affordable-bath-upgrades-fig3-900.webp", width: 1800, height: 1350, alt: "อุปกรณ์ตกแต่งเพื่อกระตุ้นให้มีชีวิตชีวา" },
    ],
    body: [
      "ถ้าห้องน้ำของคุณใช้งานมาจนดูเก่าแต่คุณยังไม่พร้อมในเรื่องค่าใช้จ่ายของการปรับปรุงห้องน้ำใหม่อย่างเต็มรูปแบบ ลองพิจารณาถึงการปรับเปลี่ยนเพียงเล็กน้อยแต่สามารถทำให้ห้องน้ำของคุณดูสวยงามขึ้นด้วยวิธีง่ายๆและยังประหยัดอีกด้วย",
      "ไม่มีสิ่งใดที่จะมอบความคุ้มค่าได้มากไปกว่าการเปลี่ยนหัวฝักบัวอาบน้ำอันเก่า ที่เริ่มใช้งานไม่ค่อยดีแล้วเสียใหม่ โดยทั่วไป ไม่จำเป็นต้องใช้มืออาชีพมาติดตั้งหรือเปลี่ยนหัวฝักบัวอาบน้ำที่ราคาไม่แพง และยังสามารถช่วยคุณประหยัดค่าน้ำได้อีกด้วย",
      "ม่านกั้นอาบน้ำที่ทำจากเนื้อผ้าหรือพลาสติก จะสะสมพวกเชื้อราและรักษาความสะอาดยาก คุณอาจลองติดตั้งประตูห้องอาบน้ำแบบบานเปลือย ที่ทำความสะอาดง่ายและยังให้ความสวยงามแก่ห้องอาบน้ำของคุณอีกด้วย",
      "อีกแนวทางหนึ่งที่มอบความรู้สึกหรูหรามีราคาให้กับห้องอาบน้ำเดิมของคุณคือเปลี่ยนราวที่ใช้ขึงม่านกั้นให้มีรูปทรงโค้งมน จะช่วยเพิ่มพื้นที่ให้มุมห้องน้ำในขณะอาบน้ำ",
      "การปรับเปลี่ยนห้องอาบน้ำให้ดูสวยงามมากขึ้นด้วยงบประมาณจำกัด คือการเปลี่ยนอุปกรณ์ประกอบห้องน้ำอันเก่าในห้องน้ำของคุณด้วยของชิ้นใหม่ที่มีสไตล์ หรืออาจเติมอุปกรณ์ประกอบห้องน้ำใหม่ๆเพื่อเพิ่มพื้นที่การใช้งานให้กับห้องอาบน้ำของคุณ",
      "ยกระดับด้วยฝารองนั่งอเนกประสงค์ ที่ให้ความโดดเด่นทั้งการใช้งานจนถึงความหรูหรา แม้ว่าจะเป็นการปรับปรุงเพียงเล็กน้อยก็สามารถรังสรรค์คุณภาพชีวิตของคุณในห้องอาบน้ำให้เพิ่มขึ้นได้",
      "การปรับเปลี่ยนนี้ สามารถตอบโจทย์ได้เป็นการชั่วคราวก่อนที่จะเริ่มดำเนินการปรับโฉมใหม่ให้ครอบคลุมทั้งหมดในอนาคต ถึงแม้ว่าจะไม่ได้ดำเนินการปรับเปลี่ยนรูปลักษณ์ใหม่ทั้งหมดให้กับห้องน้ำที่มีอยู่เดิม ก็สามารถทำให้ดูสวยงามและมีประโยชน์ใช้สอยมากขึ้น",
      "« Lihat Kiat-kiat Lain untuk Kamar Mandi",
    ],
    videos: [],
    bannerVideo: null,
  },
  {
    slug: "leap-smart-toilet",
    title: { th: "Take a Leap™ Step up to KOHLER", en: "Take a Leap™ Step up to KOHLER" },
    excerpt: { th: "Leap™ smart toilet ผสานดีไซน์เรียบหรูแบบซ่อนแทงค์น้ำเข้ากับฟังก์ชันอัจฉริยะเพื่อยกระดับกิจวัตรประจำวันของคุณให้เหนือกว่าเดิม มาพร้อมระบบดูอัลฟลัช…", en: "Leap™ smart toilet ผสานดีไซน์เรียบหรูแบบซ่อนแทงค์น้ำเข้ากับฟังก์ชันอัจฉริยะเพื่อยกระดับกิจวัตรประจำวันของคุณให้เหนือกว่าเดิม มาพร้อมระบบดูอัลฟลัช…" },
    date: CAPTURED,
    tag: "เรื่องเล่าจาก KOHLER",
    tagEn: "From KOHLER",
    space: "bath",
    coverId: "aab15367-rgb",
    source: { url: "https://www.kohler.co.th/articles/leap-smart-toilet.html", route: "/articles/leap-smart-toilet.html" },
    hero: { src: "/lifestyle/editorial/leap-smart-toilet-hero-1800.webp", srcSmall: "/lifestyle/editorial/leap-smart-toilet-hero-900.webp", width: 1800, height: 255, alt: "Take a Leap™ Step up to KOHLER" },
    cover: { src: "/lifestyle/editorial/leap-smart-toilet-fig1-1800.webp", srcSmall: "/lifestyle/editorial/leap-smart-toilet-fig1-900.webp", width: 1800, height: 255, alt: "รีโมตคอนโทรลใช้งานง่าย" },
    figures: [
      { src: "/lifestyle/editorial/leap-smart-toilet-fig1-1800.webp", srcSmall: "/lifestyle/editorial/leap-smart-toilet-fig1-900.webp", width: 1800, height: 255, alt: "รีโมตคอนโทรลใช้งานง่าย" },
      { src: "/lifestyle/editorial/leap-smart-toilet-fig2-1800.webp", srcSmall: "/lifestyle/editorial/leap-smart-toilet-fig2-900.webp", width: 1800, height: 255, alt: "เหนือระดับแห่งความสบาย" },
      { src: "/lifestyle/editorial/leap-smart-toilet-fig3-1800.webp", srcSmall: "/lifestyle/editorial/leap-smart-toilet-fig3-900.webp", width: 1800, height: 255, alt: "ระบบเป่าลมอุ่น" },
    ],
    body: [
      "Leap™ smart toilet ผสานดีไซน์เรียบหรูแบบซ่อนแทงค์น้ำเข้ากับฟังก์ชันอัจฉริยะเพื่อยกระดับกิจวัตรประจำวันของคุณให้เหนือกว่าเดิม มาพร้อมระบบดูอัลฟลัช ให้พลังการชำระล้างแบบหมุนวนทรงพลัง ทำความสะอาดได้ทั่วทั้งโถอย่างมีประสิทธิภาพ พร้อมช่วยประหยัดน้ำ ด้วยความยาวของสุภัณฑ์เพียง 680 มม. จึงเหมาะอย่างยิ่งสำหรับห้องน้ำพื้นที่จำกัด ดีไซน์บาง เรียบ มินิมอล มาพร้อมรีโมตคอนโทรลอัจฉริยะ ใช้งานง่าย",
      "ปรับอุณหภูมิฝารองนั่ง อุณหภูมิน้ำและความแรงน้ำของก้านฉีดได้",
      "ควบคุมทุกฟังก์ชันอย่างง่ายดาย ตอบสนองทุกการใช้งาน",
      "ปรับอุณหภูมิน้ำและรูปแบบสายน้ำได้ตามต้องการ มาพร้อมรูปแบบการชำระล้างที่หลากหลาย (ล้างด้านหน้า / ล้างด้านหลัง / โหมดนวด / โหมดพ่นเป็นจังหวะ)",
      "มอบประสบการณ์การใช้งานที่สบายยิ่งขึ้น ด้วยระบบเป่าลมอุ่นที่สามารถปรับอุณหภูมิได้ 3 ระดับ",
    ],
    videos: [
      { id: "J3LWUMJsR8I", title: "Introducing The New Sleek, Contemporary Design of Leap™ Smart Toilet", poster: { src: "/lifestyle/editorial/yt-J3LWUMJsR8I-640.webp", srcSmall: "/lifestyle/editorial/yt-J3LWUMJsR8I-640.webp", width: 640, height: 480, alt: "Introducing The New Sleek, Contemporary Design of Leap™ Smart Toilet" } },
      { id: "a7I-XbBRm24", title: "Level Up with Leap™ Smart Toilet", poster: { src: "/lifestyle/editorial/yt-a7I-XbBRm24-640.webp", srcSmall: "/lifestyle/editorial/yt-a7I-XbBRm24-640.webp", width: 640, height: 480, alt: "Level Up with Leap™ Smart Toilet" } },
    ],
    bannerVideo: null,
  },
];

export function getPost(slug: string) {
  return posts.find((p) => p.slug === slug);
}
