// GENERATED by scripts/scrape-kohler.mjs — do not edit by hand.
// Source: kohler.co.th product detail pages. Imagery is Kohler's and is used here for
// presentation only; see README before deploying anywhere public.

export type Category = 'kitchen' | 'bath';
export type FinishCode = string;

export type Finish = {
  code: FinishCode;
  name: { th: string; en: string };
  /** /products/<slug>/swatch-<code>.webp */
  swatch: string;
  /** average colour of the swatch chip, used as --accent */
  accent: string;
  /** /products/<slug>/<code>.webp — 1400px, background keyed out */
  image: string;
  /** same frame at 700px */
  image700: string;
};

export type Product = {
  slug: string;
  model: string;
  category: Category;
  name: { th: string; en: string };
  desc: { th: string; en: string };
  specs: { label: string; value: string }[];
  /** always >= 2 */
  finishes: Finish[];
  featured?: boolean;
  /** kept so components written against the mock data still compile */
  price: { th: string; en: string };
  /** kept for the same reason — mirrors finishes[].image */
  images: string[];
};

const ASK = { th: 'สอบถามราคา', en: 'Price on request' };

export const products: Product[] = [
  {
    slug: "components-23888t",
    model: "K-23888T",
    category: "bath",
    name: { th: "หัวก๊อกผสมอ่างล้างหน้าแบบติดผนัง ปากก๊อก-ริบบิ้น รุ่นคอมโพเนนท์", en: "Wall-mount bathroom sink faucet spout with Ribbon design, 7.0 lpm" },
    desc: { th: "คอลเล็กชั่นสุดพิเศษ เชิญชวนคุณให้มาร่วมดีไซน์ก๊อกน้ำที่เป็นดั่งซิกเนเจอร์ของคุณเอง ด้วยการผสมผสานหัวก๊อก มือบิด และพื้นผิววัสดุ ให้สะท้อนความเป็นตัวตนและรสนิยมที่ไม่ซ้ำใคร คอมโพเนนท์ คอลเล็กชั่น ดีไซน์เพื่อให้คุณได้ดีไซน์...ในสไตล์ที่เป็นคุณ", en: "Modern form meets modern function: the Components™ collection is defined by controlled forms and stark precision in every line and angle. With Components™, you are able to design your custom bath. This minimalist wall-mount bathroom sink faucet spout with Ribbon design pairs with your choice of Components™ bath faucet handles for a personalized design." },
    specs: [
      { label: "ขนาด", value: "H 78 มิลลิเมตร, W 60 มิลลิเมตร" },
      { label: "คอลเลกชัน", value: "Components™" },
      { label: "การติดตั้ง", value: "แบบติดผนัง" },
      { label: "คุณสมบัติ 1", value: "ผลิตจากทองเหลือง" },
      { label: "คุณสมบัติ 2", value: "วัสดุเคลือบผิวพิเศษจากโคห์เลอร์ คงทน เงางาม" },
      { label: "คุณสมบัติ 3", value: "ดีไซน์แบบซ่อนปากก๊อก ง่ายต่อการทำความสะอาด" },
    ],
    finishes: [
      {
        code: "AF",
        name: { th: "เฟรนช์โกลด์", en: "Vibrant® French Gold" },
        swatch: "/products/components-23888t/swatch-AF.webp",
        accent: "#F2E2C1",
        image: "/products/components-23888t/AF.webp",
        image700: "/products/components-23888t/AF-700.webp",
      },
      {
        code: "BN",
        name: { th: "นิกเกิ้ลปัดลาย", en: "Vibrant® Brushed Nickel" },
        swatch: "/products/components-23888t/swatch-BN.webp",
        accent: "#A5A29A",
        image: "/products/components-23888t/BN.webp",
        image700: "/products/components-23888t/BN-700.webp",
      },
      {
        code: "CP",
        name: { th: "โครเมี่ยม", en: "Polished Chrome" },
        swatch: "/products/components-23888t/swatch-CP.webp",
        accent: "#CDCED3",
        image: "/products/components-23888t/CP.webp",
        image700: "/products/components-23888t/CP-700.webp",
      },
      {
        code: "RGD",
        name: { th: "Vibrant Rose Gold", en: "Vibrant® Rose Gold" },
        swatch: "/products/components-23888t/swatch-RGD.webp",
        accent: "#AB8974",
        image: "/products/components-23888t/RGD.webp",
        image700: "/products/components-23888t/RGD-700.webp",
      },
      {
        code: "BRD",
        name: { th: "Vibrant Brushed Rose Gold", en: "Vibrant Brushed Rose Gold" },
        swatch: "/products/components-23888t/swatch-BRD.webp",
        accent: "#BC8B6F",
        image: "/products/components-23888t/BRD.webp",
        image700: "/products/components-23888t/BRD-700.webp",
      },
      {
        code: "BRT",
        name: { th: "Vibrant Brushed Titanium", en: "Vibrant Brushed Titanium" },
        swatch: "/products/components-23888t/swatch-BRT.webp",
        accent: "#756E6C",
        image: "/products/components-23888t/BRT.webp",
        image700: "/products/components-23888t/BRT-700.webp",
      },
    ],
    featured: true,
    price: ASK,
    images: ["/products/components-23888t/AF.webp", "/products/components-23888t/BN.webp", "/products/components-23888t/CP.webp", "/products/components-23888t/RGD.webp", "/products/components-23888t/BRD.webp", "/products/components-23888t/BRT.webp"],
  },
  {
    slug: "modulo-78023t-4",
    model: "K-78023T-4",
    category: "bath",
    name: { th: "ชุดฝาครอบและวาล์วผสมฝังกำแพงยืนอาบระบบเทอร์โมสแตทติก รุ่นโมดูโล คอมโพเนนท์", en: "Thermostatic valve and shower trim with Lever handles" },
    desc: { th: "คอลเล็กชั่นสุดพิเศษ เชิญชวนคุณให้มาร่วมดีไซน์ก๊อกน้ำที่เป็นดั่งซิกเนเจอร์ของคุณเอง ด้วยการผสมผสานหัวก๊อก มือบิด และพื้นผิววัสดุ ให้สะท้อนความเป็นตัวตนและรสนิยมที่ไม่ซ้ำใคร คอมโพเนนท์ คอลเล็กชั่น ดีไซน์เพื่อให้คุณได้ดีไซน์...ในสไตล์ที่เป็นคุณ", en: "Modern, polished, and streamlined, the Modulo™ collection provides smooth control of both temperature and volume. The Modulo™ thermostatic valve trim, featuring two modern Lever style handles, includes the valve for easy installation. Pair with other contemporary bathroom faucets and accessories for a sleek aesthetic." },
    specs: [
      { label: "ขนาด", value: "H 180 มิลลิเมตร, W 180 มิลลิเมตร" },
      { label: "คอลเลกชัน", value: "Modulo™" },
      { label: "การติดตั้ง", value: "แบบติดผนัง" },
      { label: "คุณสมบัติ 1", value: "ผลิตจากทองเหลือง" },
      { label: "คุณสมบัติ 2", value: "วัสดุเคลือบผิวพิเศษจากโคห์เลอร์ คงทน เงางาม" },
      { label: "คุณสมบัติ 3", value: "พร้อมเซรามิกวาล์วกันการรั่วซึม" },
    ],
    finishes: [
      {
        code: "AF",
        name: { th: "เฟรนช์โกลด์", en: "Vibrant® French Gold" },
        swatch: "/products/modulo-78023t-4/swatch-AF.webp",
        accent: "#F2E2C1",
        image: "/products/modulo-78023t-4/AF.webp",
        image700: "/products/modulo-78023t-4/AF-700.webp",
      },
      {
        code: "BN",
        name: { th: "นิกเกิ้ลปัดลาย", en: "Vibrant® Brushed Nickel" },
        swatch: "/products/modulo-78023t-4/swatch-BN.webp",
        accent: "#A5A29A",
        image: "/products/modulo-78023t-4/BN.webp",
        image700: "/products/modulo-78023t-4/BN-700.webp",
      },
      {
        code: "CP",
        name: { th: "โครเมี่ยม", en: "Polished Chrome" },
        swatch: "/products/modulo-78023t-4/swatch-CP.webp",
        accent: "#CDCED3",
        image: "/products/modulo-78023t-4/CP.webp",
        image700: "/products/modulo-78023t-4/CP-700.webp",
      },
      {
        code: "RGD",
        name: { th: "Vibrant Rose Gold", en: "Vibrant® Rose Gold" },
        swatch: "/products/modulo-78023t-4/swatch-RGD.webp",
        accent: "#AB8974",
        image: "/products/modulo-78023t-4/RGD.webp",
        image700: "/products/modulo-78023t-4/RGD-700.webp",
      },
      {
        code: "BRD",
        name: { th: "Vibrant Brushed Rose Gold", en: "Vibrant Brushed Rose Gold" },
        swatch: "/products/modulo-78023t-4/swatch-BRD.webp",
        accent: "#BC8B6F",
        image: "/products/modulo-78023t-4/BRD.webp",
        image700: "/products/modulo-78023t-4/BRD-700.webp",
      },
      {
        code: "BRT",
        name: { th: "Vibrant Brushed Titanium", en: "Vibrant Brushed Titanium" },
        swatch: "/products/modulo-78023t-4/swatch-BRT.webp",
        accent: "#756E6C",
        image: "/products/modulo-78023t-4/BRT.webp",
        image700: "/products/modulo-78023t-4/BRT-700.webp",
      },
    ],
    featured: true,
    price: ASK,
    images: ["/products/modulo-78023t-4/AF.webp", "/products/modulo-78023t-4/BN.webp", "/products/modulo-78023t-4/CP.webp", "/products/modulo-78023t-4/RGD.webp", "/products/modulo-78023t-4/BRD.webp", "/products/modulo-78023t-4/BRT.webp"],
  },
  {
    slug: "parallel-23472t-4",
    model: "K-23472T-4",
    category: "bath",
    name: { th: "ก๊อกผสมอ่างล้างหน้าแบบก้านโยก", en: "Single-handle bathroom sink faucet, 8.3 lpm" },
    desc: { th: "ด้วยการเจียระไนรูปทรงอย่างแม่นยำและพื้นผิวที่เรียบสนิท แสดงออกถึงความมีรสนิยม ที่แต่งเติมห้องน้ำแบบโมเดิร์นได้อย่างสมบูรณ์แบบนำความเป็นมินิมัลมาใช้ได้ลงตัวในทุก พื้นที่ รูปทรงที่แตกต่างกันสองขั้วทั้งแบบทรงกลมและจตุรัส แต่กลับหลอมรวมกันเป็น หนึ่งเดียว สะท้อนภาพที่สวยงามในทุกมุมมอง แม้แต่รายละเอียดเล็ก ๆ น้อย ๆ ก็ยังมี เอกลักษณ์เฉพาะตัว ส่งผลให้คอลเล็กชั่นนี้เป็นอีกระดับของความเลิศล้ำที่เหนือกว่า", en: "Parallel™ is the quintessential expression of today’s modern aesthetic movement. The contrast between fluid blends and sharp lines exudes sophistication and refinement. Its subtle and sensual curves invite touch, while its precise geometry gives a sense of control and precision. Parallel™ provides warmth and magnetism to any modern contemporary bathroom. True to its origins in design minimalism, Parallel™ revives a pure way to connect with the eye and the hand. This Parallel™ single-handle faucet is an impressive standout to pair with a vessel sink." },
    specs: [
      { label: "ขนาด", value: "H 196 มิลลิเมตร, W 47 มิลลิเมตร" },
      { label: "คอลเลกชัน", value: "Parallel™" },
      { label: "การติดตั้ง", value: "ตั้งบนเคาน์เตอร์" },
      { label: "คุณสมบัติ 1", value: "ผลิตจากทองเหลือง" },
      { label: "คุณสมบัติ 2", value: "วัสดุเคลือบผิวพิเศษของโคห์เลอร์ คงทน เงางาม" },
      { label: "คุณสมบัติ 3", value: "เซรามิกวาล์วป้องกันการรั่วซึม รับประกันตลอดอายุการใช้งาน" },
    ],
    finishes: [
      {
        code: "AF",
        name: { th: "เฟรนช์โกลด์", en: "Vibrant® French Gold" },
        swatch: "/products/parallel-23472t-4/swatch-AF.webp",
        accent: "#F2E2C1",
        image: "/products/parallel-23472t-4/AF.webp",
        image700: "/products/parallel-23472t-4/AF-700.webp",
      },
      {
        code: "CP",
        name: { th: "โครเมี่ยม", en: "Polished Chrome" },
        swatch: "/products/parallel-23472t-4/swatch-CP.webp",
        accent: "#CDCED3",
        image: "/products/parallel-23472t-4/CP.webp",
        image700: "/products/parallel-23472t-4/CP-700.webp",
      },
      {
        code: "RGD",
        name: { th: "Vibrant Rose Gold", en: "Vibrant® Rose Gold" },
        swatch: "/products/parallel-23472t-4/swatch-RGD.webp",
        accent: "#AB8974",
        image: "/products/parallel-23472t-4/RGD.webp",
        image700: "/products/parallel-23472t-4/RGD-700.webp",
      },
    ],
    featured: true,
    price: ASK,
    images: ["/products/parallel-23472t-4/AF.webp", "/products/parallel-23472t-4/CP.webp", "/products/parallel-23472t-4/RGD.webp"],
  },
  {
    slug: "statement-2-19-26324t",
    model: "K-26324T",
    category: "bath",
    name: { th: "ก้านฝักบัวติดผนัง 2 ระดับ 19\" รุ่น สเตทเมนท์", en: "483 mm wall-mount two-function rainhead arm and flange" },
    desc: { th: "สร้างบรรยากาศแสนดื่มด่ำในการชำระล้าง นวด และฟื้นฟูเรือนร่าง ด้วยรูปแบบการ สเปรย์ที่หลากหลาย และเหมาะสมในแต่ละความต้องการ การตั้งค่าสำหรับควบคุมสายน้ำได้รับการออกแบบมาอย่างพิถีพิถัน เพื่อมอบช่วงเวลาแห่งการเปลี่ยนผ่านสู่ความสุขให้น่าจดจำในทุก ๆ ครั้งที่คุณอาบน้ำ", en: "KOHLER showering products offer luxurious water delivery for any custom or traditional showering environment. This 483 mm rainhead arm with flange provides a solid wall-mount for two-function rainheads. With durable brass construction and minimalist design, this shower accessory is versatile enough for any bathroom design." },
    specs: [
      { label: "ขนาด", value: "H 64 มิลลิเมตร, W 99 มิลลิเมตร" },
      { label: "คอลเลกชัน", value: "Statement™" },
      { label: "การติดตั้ง", value: "แบบติดผนัง" },
      { label: "คุณสมบัติ 1", value: "ผลิตจากทองเหลือง" },
      { label: "คุณสมบัติ 2", value: "วัสดุเคลือบผิวพิเศษของโคห์เลอร์ คงทน เงางาม" },
      { label: "คุณสมบัติ 3", value: "เกลียวทางน้ำเข้า G1/2\"" },
    ],
    finishes: [
      {
        code: "BRD",
        name: { th: "Vibrant Brushed Rose Gold", en: "Vibrant Brushed Rose Gold" },
        swatch: "/products/statement-2-19-26324t/swatch-BRD.webp",
        accent: "#BC8B6F",
        image: "/products/statement-2-19-26324t/BRD.webp",
        image700: "/products/statement-2-19-26324t/BRD-700.webp",
      },
      {
        code: "BRT",
        name: { th: "Vibrant Brushed Titanium", en: "Vibrant Brushed Titanium" },
        swatch: "/products/statement-2-19-26324t/swatch-BRT.webp",
        accent: "#756E6C",
        image: "/products/statement-2-19-26324t/BRT.webp",
        image700: "/products/statement-2-19-26324t/BRT-700.webp",
      },
    ],
    price: ASK,
    images: ["/products/statement-2-19-26324t/BRD.webp", "/products/statement-2-19-26324t/BRT.webp"],
  },
  {
    slug: "occasion-8-ex27100t-3",
    model: "K-EX27100T-3",
    category: "bath",
    name: { th: "ก๊อกผสมอ่างล้างหน้าเซ็นเตอร์ 8” (มือบิดแบบครอส) รุ่นโอเคชัน", en: "Widespread bathroom sink faucet with cross handles and Cane spout, 8.3 lpm" },
    desc: { th: "ใส่ความเป็นแฟชั่น สร้างสรรค์จุดสนใจ โอเคชัน คอลเลคชั่น ได้รับแรงบันดาลใจจากแฟชั่นชั้นสูงและความงามอันแสนเย้ายวนใจของ ยุคทองแห่งฮอลลีวูดด้วยการออกแบบอย่างไร้ที่ติ สะกดทุกสายตา ตั้งแต่มุมโค้งมนไปจนถึง ความวาววามของฐานก๊อก จึงเปี่ยมด้วยความสง่างาม ประณีตบรรจง และสะท้อนยุคสมัย แห่งความมีเสน่ห์ เพื่อเป็นจุดศูนย์กลางความสนใจอย่างแท้จริง", en: "Unapologetically luxurious and truly unforgettable, Occasion bathroom faucets and accessories draw inspiration from 1960s Hollywood glamour and extravagance. Fashioned after the era’s sleek dress lines and bold car designs, the Occasion collection reflects graceful elegance, blending classic midcentury and modern design. Customize your bathroom with the collection’s distinctive pentagonal accents, faceted bases, flowing lines, and delicate edges. Sleek and statuesque, the Occasion widespread bathroom sink faucet with cross handles and Cane spout is as fashionable as it is functional." },
    specs: [
      { label: "ขนาด", value: "Rough In/Spec Sheet Installation Instruction ผลการทดสอบรังสี รายการที่ตรงกัน" },
      { label: "คอลเลกชัน", value: "Occasion™" },
      { label: "คุณสมบัติ 1", value: "ผลิตจากทองเหลือง" },
      { label: "คุณสมบัติ 2", value: "เซรามิกวาล์วป้องกันการรั่่วซึม รับประกันตลอดอายุการใช้งาน" },
      { label: "คุณสมบัติ 3", value: "วัสดุเคลือบผิวพิเศษจากโคห์เลอร์คงทนเงางาม" },
    ],
    finishes: [
      {
        code: "BRD",
        name: { th: "Vibrant Brushed Rose Gold", en: "Vibrant Brushed Rose Gold" },
        swatch: "/products/occasion-8-ex27100t-3/swatch-BRD.webp",
        accent: "#BC8B6F",
        image: "/products/occasion-8-ex27100t-3/BRD.webp",
        image700: "/products/occasion-8-ex27100t-3/BRD-700.webp",
      },
      {
        code: "BRT",
        name: { th: "Vibrant Brushed Titanium", en: "Vibrant Brushed Titanium" },
        swatch: "/products/occasion-8-ex27100t-3/swatch-BRT.webp",
        accent: "#756E6C",
        image: "/products/occasion-8-ex27100t-3/BRT.webp",
        image700: "/products/occasion-8-ex27100t-3/BRT-700.webp",
      },
    ],
    price: ASK,
    images: ["/products/occasion-8-ex27100t-3/BRD.webp", "/products/occasion-8-ex27100t-3/BRT.webp"],
  },
  {
    slug: "components-77959t-4a",
    model: "K-77959T-4A",
    category: "bath",
    name: { th: "ก๊อกผสมอ่างล้างหน้าทรงสูงรูเดี่ยวแบบก้านโยก รุ่นคอมโพเนนท์", en: "Tall single-handle bathroom sink faucet with Tube spout and Pin handle, 5.7 lpm" },
    desc: { th: "คอลเล็กชั่นสุดพิเศษ เชิญชวนคุณให้มาร่วมดีไซน์ก๊อกน้ำที่เป็นดั่งซิกเนเจอร์ของคุณเอง ด้วยการผสมผสานหัวก๊อก มือบิด และพื้นผิววัสดุ ให้สะท้อนความเป็นตัวตนและรสนิยมที่ไม่ซ้ำใคร คอมโพเนนท์ คอลเล็กชั่น ดีไซน์เพื่อให้คุณได้ดีไซน์...ในสไตล์ที่เป็นคุณ", en: "Modern form meets modern function: the Components™ collection is defined by controlled forms and stark precision in every line and angle. With Components, you are able to design your custom bath. This single-hole bathroom sink faucet with Tube spout features a slim, elegant Pin handle that is easy to control with one hand. The tall height of this faucet beautifully complements vessel-style sinks. Coordinate this sink faucet with Components™ shower faucets and accessories to create a personalized design." },
    specs: [
      { label: "ขนาด", value: "H 286 มิลลิเมตร, W 48 มิลลิเมตร" },
      { label: "คอลเลกชัน", value: "Components™" },
      { label: "การติดตั้ง", value: "ตั้งบนเคาน์เตอร์" },
      { label: "คุณสมบัติ 1", value: "ผลิตจากทองเหลือง" },
      { label: "คุณสมบัติ 2", value: "วัสดเคลือบผิวพิเศษจากโคห์เลอร์ คงทน เงางาม" },
      { label: "คุณสมบัติ 3", value: "สายน้ำดีขนาด G1/2\" ติดตั้งง่าย" },
    ],
    finishes: [
      {
        code: "CP",
        name: { th: "โครเมี่ยม", en: "Polished Chrome" },
        swatch: "/products/components-77959t-4a/swatch-CP.webp",
        accent: "#CDCED3",
        image: "/products/components-77959t-4a/CP.webp",
        image700: "/products/components-77959t-4a/CP-700.webp",
      },
      {
        code: "AF",
        name: { th: "เฟรนช์โกลด์", en: "Vibrant® French Gold" },
        swatch: "/products/components-77959t-4a/swatch-AF.webp",
        accent: "#F2E2C1",
        image: "/products/components-77959t-4a/AF.webp",
        image700: "/products/components-77959t-4a/AF-700.webp",
      },
      {
        code: "RGD",
        name: { th: "Vibrant Rose Gold", en: "Vibrant® Rose Gold" },
        swatch: "/products/components-77959t-4a/swatch-RGD.webp",
        accent: "#AB8974",
        image: "/products/components-77959t-4a/RGD.webp",
        image700: "/products/components-77959t-4a/RGD-700.webp",
      },
      {
        code: "BN",
        name: { th: "นิกเกิ้ลปัดลาย", en: "Vibrant® Brushed Nickel" },
        swatch: "/products/components-77959t-4a/swatch-BN.webp",
        accent: "#A5A29A",
        image: "/products/components-77959t-4a/BN.webp",
        image700: "/products/components-77959t-4a/BN-700.webp",
      },
      {
        code: "BRD",
        name: { th: "Vibrant Brushed Rose Gold", en: "Vibrant Brushed Rose Gold" },
        swatch: "/products/components-77959t-4a/swatch-BRD.webp",
        accent: "#BC8B6F",
        image: "/products/components-77959t-4a/BRD.webp",
        image700: "/products/components-77959t-4a/BRD-700.webp",
      },
      {
        code: "BRT",
        name: { th: "Vibrant Brushed Titanium", en: "Vibrant Brushed Titanium" },
        swatch: "/products/components-77959t-4a/swatch-BRT.webp",
        accent: "#756E6C",
        image: "/products/components-77959t-4a/BRT.webp",
        image700: "/products/components-77959t-4a/BRT-700.webp",
      },
    ],
    featured: true,
    price: ASK,
    images: ["/products/components-77959t-4a/CP.webp", "/products/components-77959t-4a/AF.webp", "/products/components-77959t-4a/RGD.webp", "/products/components-77959t-4a/BN.webp", "/products/components-77959t-4a/BRD.webp", "/products/components-77959t-4a/BRT.webp"],
  },
  {
    slug: "modulo-78024t-4",
    model: "K-78024T-4",
    category: "bath",
    name: { th: "Modulo™ |", en: "Thermostatic bath & shower valve and trim with Lever handles" },
    desc: { th: "คอมโพเนนท์ คอลเล็คชั่นที่สัมผัสได้ถึงความทันสมัย เปิดโอกาสที่ให้คุณสร้างสรรค์ดีไซน์ได้อย่างอิสระ ทั้งหัวก๊อก มือจับหรือพื้นผิววัสดุ ให้ตรงตามรสนิยมและสไตล์ของตัวเอง ไม่ว่าจะเป็นรูปแบบใดก็สวยรับกันทั้งก๊อกน้ำ ชุดฝักบัวและอุปกรณ์ประกอบห้องน้ำ", en: "Modern, polished, and streamlined, the Components™ Modulo™ collection provides smooth control of both temperature and volume. This thermostatic bath and shower trim, featuring two modern lever style handles, includes the valve for easy installation. Pair with your Components™ shower faucets and accessories for a customized aesthetic." },
    specs: [
      { label: "ขนาด", value: "H 80 มิลลิเมตร, W 180 มิลลิเมตร" },
      { label: "คอลเลกชัน", value: "Modulo™" },
      { label: "การติดตั้ง", value: "แบบติดผนัง" },
      { label: "คุณสมบัติ 1", value: "ผลิตจากทองเหลือง" },
      { label: "คุณสมบัติ 2", value: "มือบิดแบบก้านโยกพร้อมฝาครอบและมือบิด" },
      { label: "คุณสมบัติ 3", value: "พร้อมเซรามิกวาล์วกันการรั่วซึม" },
    ],
    finishes: [
      {
        code: "AF",
        name: { th: "เฟรนช์โกลด์", en: "Vibrant® French Gold" },
        swatch: "/products/modulo-78024t-4/swatch-AF.webp",
        accent: "#F2E2C1",
        image: "/products/modulo-78024t-4/AF.webp",
        image700: "/products/modulo-78024t-4/AF-700.webp",
      },
      {
        code: "BN",
        name: { th: "นิกเกิ้ลปัดลาย", en: "Vibrant® Brushed Nickel" },
        swatch: "/products/modulo-78024t-4/swatch-BN.webp",
        accent: "#A5A29A",
        image: "/products/modulo-78024t-4/BN.webp",
        image700: "/products/modulo-78024t-4/BN-700.webp",
      },
      {
        code: "CP",
        name: { th: "โครเมี่ยม", en: "Polished Chrome" },
        swatch: "/products/modulo-78024t-4/swatch-CP.webp",
        accent: "#CDCED3",
        image: "/products/modulo-78024t-4/CP.webp",
        image700: "/products/modulo-78024t-4/CP-700.webp",
      },
      {
        code: "RGD",
        name: { th: "Vibrant Rose Gold", en: "Vibrant® Rose Gold" },
        swatch: "/products/modulo-78024t-4/swatch-RGD.webp",
        accent: "#AB8974",
        image: "/products/modulo-78024t-4/RGD.webp",
        image700: "/products/modulo-78024t-4/RGD-700.webp",
      },
    ],
    featured: true,
    price: ASK,
    images: ["/products/modulo-78024t-4/AF.webp", "/products/modulo-78024t-4/BN.webp", "/products/modulo-78024t-4/CP.webp", "/products/modulo-78024t-4/RGD.webp"],
  },
  {
    slug: "parallel-23475t-4",
    model: "K-23475T-4",
    category: "bath",
    name: { th: "ก๊อกผสมอ่างล้างหน้าทรงสูงแบบก้านโยก", en: "Tall single-handle bathroom sink faucet, 8.3 lpm" },
    desc: { th: "ด้วยการเจียระไนรูปทรงอย่างแม่นยำและพื้นผิวที่เรียบสนิท แสดงออกถึงความมีรสนิยม ที่แต่งเติมห้องน้ำแบบโมเดิร์นได้อย่างสมบูรณ์แบบนำความเป็นมินิมัลมาใช้ได้ลงตัวในทุก พื้นที่ รูปทรงที่แตกต่างกันสองขั้วทั้งแบบทรงกลมและจตุรัส แต่กลับหลอมรวมกันเป็น หนึ่งเดียว สะท้อนภาพที่สวยงามในทุกมุมมอง แม้แต่รายละเอียดเล็ก ๆ น้อย ๆ ก็ยังมี เอกลักษณ์เฉพาะตัว ส่งผลให้คอลเล็กชั่นนี้เป็นอีกระดับของความเลิศล้ำที่เหนือกว่า", en: "Parallel™ is the quintessential expression of today’s modern aesthetic movement. The contrast between fluid blends and sharp lines exudes sophistication and refinement. Its subtle and sensual curves invite touch, while its precise geometry gives a sense of control and precision. Parallel™ provides warmth and magnetism to any modern contemporary bathroom. True to its origins in design minimalism, Parallel™ revives a pure way to connect with the eye and the hand. This Parallel™ tall faucet is an impressive standout to pair with a vessel sink." },
    specs: [
      { label: "ขนาด", value: "H 261 มิลลิเมตร, W 48 มิลลิเมตร" },
      { label: "คอลเลกชัน", value: "Parallel™" },
      { label: "การติดตั้ง", value: "ตั้งบนเคาน์เตอร์" },
      { label: "คุณสมบัติ 1", value: "ผลิตจากทองเหลือง" },
      { label: "คุณสมบัติ 2", value: "วัสดุเคลือบผิวพิเศษของโคห์เลอร์ คงทน เงางาม" },
      { label: "คุณสมบัติ 3", value: "เซรามิกวาล์วป้องกันการรั่วซึม รับประกันตลอดอายุการใช้งาน" },
    ],
    finishes: [
      {
        code: "AF",
        name: { th: "เฟรนช์โกลด์", en: "Vibrant® French Gold" },
        swatch: "/products/parallel-23475t-4/swatch-AF.webp",
        accent: "#F2E2C1",
        image: "/products/parallel-23475t-4/AF.webp",
        image700: "/products/parallel-23475t-4/AF-700.webp",
      },
      {
        code: "CP",
        name: { th: "โครเมี่ยม", en: "Polished Chrome" },
        swatch: "/products/parallel-23475t-4/swatch-CP.webp",
        accent: "#CDCED3",
        image: "/products/parallel-23475t-4/CP.webp",
        image700: "/products/parallel-23475t-4/CP-700.webp",
      },
      {
        code: "RGD",
        name: { th: "Vibrant Rose Gold", en: "Vibrant® Rose Gold" },
        swatch: "/products/parallel-23475t-4/swatch-RGD.webp",
        accent: "#AB8974",
        image: "/products/parallel-23475t-4/RGD.webp",
        image700: "/products/parallel-23475t-4/RGD-700.webp",
      },
    ],
    price: ASK,
    images: ["/products/parallel-23475t-4/AF.webp", "/products/parallel-23475t-4/CP.webp", "/products/parallel-23475t-4/RGD.webp"],
  },
  {
    slug: "occasion-ex27106t-4",
    model: "K-EX27106T-4",
    category: "bath",
    name: { th: "ก๊อกผสมลงอ่างอาบน้ำพร้อมฝักบัวสายอ่อน รุ่นโอเคชัน", en: "Deck-mount single-handle bath faucet with handshower, Straight spout with diverter" },
    desc: { th: "ใส่ความเป็นแฟชั่น สร้างสรรค์จุดสนใจ โอเคชัน คอลเลคชั่น ได้รับแรงบันดาลใจจากแฟชั่นชั้นสูงและความงามอันแสนเย้ายวนใจของ ยุคทองแห่งฮอลลีวูดด้วยการออกแบบอย่างไร้ที่ติ สะกดทุกสายตา ตั้งแต่มุมโค้งมนไปจนถึง ความวาววามของฐานก๊อก จึงเปี่ยมด้วยความสง่างาม ประณีตบรรจง และสะท้อนยุคสมัย แห่งความมีเสน่ห์ เพื่อเป็นจุดศูนย์กลางความสนใจอย่างแท้จริง", en: "Unapologetically luxurious and truly unforgettable, Occasion bathroom faucets and accessories draw inspiration from 1960s Hollywood glamour and extravagance. Fashioned after the era’s sleek dress lines and bold car designs, the Occasion collection reflects graceful elegance, blending classic midcentury and modern design. Customize your bathroom with the collection’s distinctive pentagonal accents, faceted bases, flowing lines, and delicate edges. Sleek and statuesque, the Occasion deck-mount single-handle bath faucet with Statement™ handshower, Straight spout, and diverter is as fashionable as it is functional." },
    specs: [
      { label: "ขนาด", value: "H 183 มิลลิเมตร, W 400 มิลลิเมตร" },
      { label: "คอลเลกชัน", value: "Occasion™" },
      { label: "การติดตั้ง", value: "ตั้งบนเคาน์เตอร์" },
      { label: "คุณสมบัติ 1", value: "ผลิตจากทองเหลือง" },
      { label: "คุณสมบัติ 2", value: "เซรามิกวาล์วป้องกันการรั่วซึม รับประกันตลอดอายุการใช้งาน" },
      { label: "คุณสมบัติ 3", value: "วัสดุเคลือบผิวพิเศษจากโคห์เลอร์ คงทน เงางาม" },
    ],
    finishes: [
      {
        code: "BRD",
        name: { th: "Vibrant Brushed Rose Gold", en: "Vibrant Brushed Rose Gold" },
        swatch: "/products/occasion-ex27106t-4/swatch-BRD.webp",
        accent: "#BC8B6F",
        image: "/products/occasion-ex27106t-4/BRD.webp",
        image700: "/products/occasion-ex27106t-4/BRD-700.webp",
      },
      {
        code: "BRT",
        name: { th: "Vibrant Brushed Titanium", en: "Vibrant Brushed Titanium" },
        swatch: "/products/occasion-ex27106t-4/swatch-BRT.webp",
        accent: "#756E6C",
        image: "/products/occasion-ex27106t-4/BRT.webp",
        image700: "/products/occasion-ex27106t-4/BRT-700.webp",
      },
    ],
    price: ASK,
    images: ["/products/occasion-ex27106t-4/BRD.webp", "/products/occasion-ex27106t-4/BRT.webp"],
  },
  {
    slug: "parallel-23493t-4",
    model: "K-23493T-4",
    category: "bath",
    name: { th: "ก๊อกผสมยืนอาบแบบติดผนังพร้อมฝักบัวสายอ่อน", en: "Exposed wall-mount shower only faucet" },
    desc: { th: "ด้วยการเจียระไนรูปทรงอย่างแม่นยำและพื้นผิวที่เรียบสนิท แสดงออกถึงความมีรสนิยม ที่แต่งเติมห้องน้ำแบบโมเดิร์นได้อย่างสมบูรณ์แบบนำความเป็นมินิมัลมาใช้ได้ลงตัวในทุก พื้นที่ รูปทรงที่แตกต่างกันสองขั้วทั้งแบบทรงกลมและจตุรัส แต่กลับหลอมรวมกันเป็น หนึ่งเดียว สะท้อนภาพที่สวยงามในทุกมุมมอง แม้แต่รายละเอียดเล็ก ๆ น้อย ๆ ก็ยังมี เอกลักษณ์เฉพาะตัว ส่งผลให้คอลเล็กชั่นนี้เป็นอีกระดับของความเลิศล้ำที่เหนือกว่า", en: "" },
    specs: [
      { label: "ขนาด", value: "Rough In/Spec Sheet Installation Instruction รายการที่ตรงกัน" },
      { label: "คอลเลกชัน", value: "Parallel™" },
      { label: "การติดตั้ง", value: "แบบติดผนัง" },
      { label: "คุณสมบัติ 1", value: "เซรามิกวาล์วป้องกันการรั่วซึม รับประกันตลอดอายุการใช้งาน" },
      { label: "คุณสมบัติ 2", value: "วัสดุเคลือบผิวพิเศษของโคห์เลอร์ คงทน เงางาม" },
      { label: "คุณสมบัติ 3", value: "พร้อมฝักบัวสายอ่อนปรับสายน้ำ 3 ระดับ" },
    ],
    finishes: [
      {
        code: "AF",
        name: { th: "เฟรนช์โกลด์", en: "Vibrant® French Gold" },
        swatch: "/products/parallel-23493t-4/swatch-AF.webp",
        accent: "#F2E2C1",
        image: "/products/parallel-23493t-4/AF.webp",
        image700: "/products/parallel-23493t-4/AF-700.webp",
      },
      {
        code: "CP",
        name: { th: "โครเมี่ยม", en: "Polished Chrome" },
        swatch: "/products/parallel-23493t-4/swatch-CP.webp",
        accent: "#CDCED3",
        image: "/products/parallel-23493t-4/CP.webp",
        image700: "/products/parallel-23493t-4/CP-700.webp",
      },
      {
        code: "RGD",
        name: { th: "Vibrant Rose Gold", en: "Vibrant® Rose Gold" },
        swatch: "/products/parallel-23493t-4/swatch-RGD.webp",
        accent: "#AB8974",
        image: "/products/parallel-23493t-4/RGD.webp",
        image700: "/products/parallel-23493t-4/RGD-700.webp",
      },
    ],
    price: ASK,
    images: ["/products/parallel-23493t-4/AF.webp", "/products/parallel-23493t-4/CP.webp", "/products/parallel-23493t-4/RGD.webp"],
  },
  {
    slug: "modulo-73101t-b4",
    model: "K-73101T-B4",
    category: "bath",
    name: { th: "ชุดฝาครอบและวาล์วผสมฝังกำแพงยืนอาบโมดูโล รุ่น คอมโพส", en: "Recessed non-thermostatic shower valve and trim with Lever handle" },
    desc: { th: "เจตนารมณ์แห่งการดีไซน์ไร้ซึ่งกาลเวลา ชุดก๊อกน้ำคอมโพส คือนิยามความงามการ ออกแบบในวิถีของความเรียบง่ายที่งดงามเหนือคำบรรยาย สไตล์มินิมัลลิสต์ด้วยการลด ทอนส่วนที่ไม่จำเป็นออก จนได้ผลลัพธ์อันทรงเสน่ห์ การันตีด้วยรางวัล Reddot Design Award ให้คุณเติมเต็มสุนทรียภาพให้ห้องน้ำของคุณ", en: "Modern, polished, and streamlined, the Modulo™ collection provides smooth control of both temperature and volume. The Modulo™ shower trim, featuring a Lever style handle, includes the valve for easy installation. Pair it with contemporary showering components for a sleek aesthetic." },
    specs: [
      { label: "ขนาด", value: "H 166 มิลลิเมตร, W 74 มิลลิเมตร" },
      { label: "คอลเลกชัน", value: "Modulo™" },
      { label: "การติดตั้ง", value: "ฝังผนัง" },
      { label: "คุณสมบัติ 1", value: "ผลิตจากโลหะ" },
      { label: "คุณสมบัติ 2", value: "วัสดุเคลื่อบผิวพิเศษของโคห์เลอร์ คงทน เงางาม" },
      { label: "คุณสมบัติ 3", value: "เซรามิกวาล์วป้องกันการรั่วซึม รับประกันตลอดอายุการใช้งาน" },
    ],
    finishes: [
      {
        code: "BRD",
        name: { th: "Vibrant Brushed Rose Gold", en: "Vibrant Brushed Rose Gold" },
        swatch: "/products/modulo-73101t-b4/swatch-BRD.webp",
        accent: "#BC8B6F",
        image: "/products/modulo-73101t-b4/BRD.webp",
        image700: "/products/modulo-73101t-b4/BRD-700.webp",
      },
      {
        code: "BRT",
        name: { th: "Vibrant Brushed Titanium", en: "Vibrant Brushed Titanium" },
        swatch: "/products/modulo-73101t-b4/swatch-BRT.webp",
        accent: "#756E6C",
        image: "/products/modulo-73101t-b4/BRT.webp",
        image700: "/products/modulo-73101t-b4/BRT-700.webp",
      },
    ],
    price: ASK,
    images: ["/products/modulo-73101t-b4/BRD.webp", "/products/modulo-73101t-b4/BRT.webp"],
  },
  {
    slug: "components-8-77965t",
    model: "K-77965T",
    category: "bath",
    name: { th: "หัวก๊อกผสมอ่างล้างหน้าทรงสูงเซ็นเตอร์ 8\" ปากก๊อก-ทูบ รุ่นคอมโพเนนท์", en: "Tall bathroom sink faucet spout with Tube design, 4.5 lpm" },
    desc: { th: "คอลเล็กชั่นสุดพิเศษ เชิญชวนคุณให้มาร่วมดีไซน์ก๊อกน้ำที่เป็นดั่งซิกเนเจอร์ของคุณเอง ด้วยการผสมผสานหัวก๊อก มือบิด และพื้นผิววัสดุ ให้สะท้อนความเป็นตัวตนและรสนิยมที่ไม่ซ้ำใคร คอมโพเนนท์ คอลเล็กชั่น ดีไซน์เพื่อให้คุณได้ดีไซน์...ในสไตล์ที่เป็นคุณ", en: "Modern form meets modern function: the KOHLER® Components™ collection is defined by controlled forms and stark precision in every line and angle. With Components™, you design your custom bathroom. Choose a spout, handles, and finish to build your own signature modern look. Minimalist and statuesque, this Tube spout features a tall height that complements vessel-style sinks. Pair it with your choice of Components™ sink faucet handles for a personalized design." },
    specs: [
      { label: "ขนาด", value: "H 368 มิลลิเมตร, W 60 มิลลิเมตร" },
      { label: "คอลเลกชัน", value: "Components™" },
      { label: "คุณสมบัติ 1", value: "ผลิตจากทองเหลือง" },
      { label: "คุณสมบัติ 2", value: "วัสดุเคลือบผิวพิเศษจากโคห์เลอร์ คงทน เงางาม" },
      { label: "คุณสมบัติ 3", value: "สายน้ำดีขนาด G1/2\" ติดตั้งง่าย" },
    ],
    finishes: [
      {
        code: "CP",
        name: { th: "โครเมี่ยม", en: "Polished Chrome" },
        swatch: "/products/components-8-77965t/swatch-CP.webp",
        accent: "#CDCED3",
        image: "/products/components-8-77965t/CP.webp",
        image700: "/products/components-8-77965t/CP-700.webp",
      },
      {
        code: "AF",
        name: { th: "เฟรนช์โกลด์", en: "Vibrant® French Gold" },
        swatch: "/products/components-8-77965t/swatch-AF.webp",
        accent: "#F2E2C1",
        image: "/products/components-8-77965t/AF.webp",
        image700: "/products/components-8-77965t/AF-700.webp",
      },
      {
        code: "RGD",
        name: { th: "Vibrant Rose Gold", en: "Vibrant® Rose Gold" },
        swatch: "/products/components-8-77965t/swatch-RGD.webp",
        accent: "#AB8974",
        image: "/products/components-8-77965t/RGD.webp",
        image700: "/products/components-8-77965t/RGD-700.webp",
      },
      {
        code: "BN",
        name: { th: "นิกเกิ้ลปัดลาย", en: "Vibrant® Brushed Nickel" },
        swatch: "/products/components-8-77965t/swatch-BN.webp",
        accent: "#A5A29A",
        image: "/products/components-8-77965t/BN.webp",
        image700: "/products/components-8-77965t/BN-700.webp",
      },
      {
        code: "BRD",
        name: { th: "Vibrant Brushed Rose Gold", en: "Vibrant Brushed Rose Gold" },
        swatch: "/products/components-8-77965t/swatch-BRD.webp",
        accent: "#BC8B6F",
        image: "/products/components-8-77965t/BRD.webp",
        image700: "/products/components-8-77965t/BRD-700.webp",
      },
      {
        code: "BRT",
        name: { th: "Vibrant Brushed Titanium", en: "Vibrant Brushed Titanium" },
        swatch: "/products/components-8-77965t/swatch-BRT.webp",
        accent: "#756E6C",
        image: "/products/components-8-77965t/BRT.webp",
        image700: "/products/components-8-77965t/BRT-700.webp",
      },
    ],
    featured: true,
    price: ASK,
    images: ["/products/components-8-77965t/CP.webp", "/products/components-8-77965t/AF.webp", "/products/components-8-77965t/RGD.webp", "/products/components-8-77965t/BN.webp", "/products/components-8-77965t/BRD.webp", "/products/components-8-77965t/BRT.webp"],
  },
];

export const featuredProducts = products.filter((p) => p.featured);

export function getProduct(slug: string) {
  return products.find((p) => p.slug === slug);
}

export function relatedProducts(slug: string, n = 3) {
  const cur = getProduct(slug);
  if (!cur) return [];
  return products.filter((p) => p.category === cur.category && p.slug !== slug).slice(0, n);
}
